ukui/ukui-control-center

- panels/default-app/default-app.c
The icons of all combos of default-app panel can't display completely.
> Fixed Bug:

- debian/control
- plugins/plugins.pro
* UKylin2020文件管理器使用peony-qt，功能未适配，暂时屏蔽使用到peony的三个功能
* 增加编译依赖libinterfaceclient-dev
> [hebing]适配UKylin2020版本，屏蔽三个功能解决无法启动问题；增加编译依赖

- shell/mainwindow.cpp
- shell/shell.pro
* 时间和日期依赖ukui-indicators的gsettings，社区不允许强依赖所以在mainwindowns做xml文件判断，防止段错误
> [hebing]加载插件时，对xml文件是否存在做判断防止段错误(时间和日期的依赖)

- shell/mainwindow.cpp
fix #22.If you click return button on the top left, it should return current page to the control panel homepage.
> Fix the return button on the top left did't work

- plugins/personalized/theme/theme.cpp
First time click into dialog personalized-theme, then clicked cursorTheme will crash(#54). Because previousWidget is a null pointer.
> fix clicked personalized-theme-cursorTheme crashed

- shell/modulepagewidget.cpp
when leftListWidget current item is not change,  setCurrentItem  will do nothing(#73, #71). this is the reason why content page is not uodate. To make sure QlistWidget always send currentItemChanged signal, we need to emit signal.
> fix switching the first level menu, the content page not update

- plugins/time-language/datetime/worldMap/zoneinfo.h
```
worldMap/zoneinfo.cpp: In member function ‘QString ZoneInfo::readRile(const QString&)’:
worldMap/zoneinfo.cpp:10:5: error: ‘QFile’ was not declared in this scope
10 |     QFile file(filepath);
|     ^~~~~
worldMap/zoneinfo.cpp:11:8: error: ‘file’ was not declared in this scope; did you mean ‘fileno’?
11 |     if(file.exists()) {
|        ^~~~
|        fileno
worldMap/zoneinfo.cpp:24:1: warning: control reaches end of non-void function [-Wreturn-type]
24 | }
| ^
make[2]: *** [Makefile:1366: zoneinfo.o] Error 1
```
> Fix build errors about QFile not declared

- plugins/personalized/desktop/desktop.cpp
* hide start menu fullscreen settings because no support
> hide start menu fullscreen settings @smiley286

- plugins/account/networkaccount/editpassdialog.cpp
- plugins/account/networkaccount/editpassdialog.h
- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/maindialog.h
删除了自带的Frameless框拖动效果，使用主题拖动效果
Delete the original movable effect of frameless widget , and change to use the theme's frameless widget effect.
> Movable control change to theme's control

- plugins/system/defaultapp/defaultapp.cpp
Bug: 17029 Firefox浏览器出现在“图像查看器”中
Link: http://172.17.66.192/biz/bug-view-17029.html
> Fix: Remove browser from image viewer

- shell/mainwindow.cpp
修复主窗口被拖拽后，点击任意按钮会导致主窗口再次跟随鼠标自动拖拽的bug。
> Fix:MainWindow automatically dragging with the mouse.

- plugins/system/display/declarative/qmlscreen.cpp
修复:多屏下拖拽显示器小窗口可将其拖拽出窗口范围的BUG。
Link: http://172.17.66.192/biz/bug-view-19679.html
> Fix:Limit the draging area of screens in the QQuickWidget.

- plugins/system/display/widget.cpp
Description: KScreen::OutputPtr interface's error
Log: KScreen::OutputPtr获取屏幕大小为-1错误
Bug: http://pm.kylin.com/biz/bug-view-32839.html
> fix(display): libkscreen interface error

- plugins/personalized/desktop/desktop.cpp
> 修改显示在托盘上的图标问题

- plugins/personalized/desktop/desktop.cpp
- shell/ukccabout.cpp
解决系统环境英文状态下，控制面板个性化显示在托盘上的图标为空问题；解决控制面板关于中字体可编辑问题；
> Solve the problem that the icon displayed on the tray is empty in the English state and the problem that the introduction font can be deleted.

- shell/mainwindow.cpp
Description: 鼠标点击搜索框以外的地方时，搜索框清除焦点
Log: Change <bool MainWindow::eventFilter(QObject *watched, QEvent *event){}>
> fix(mainWindow): clear m_searchWidget's focus

- plugins/system/display/widget.cpp
- plugins/system/display/widget.h
Description: the ukcc's dispaly rotation is different from kds
Log:与win+p显示的位置不同
Bug: http://pm.kylin.com/biz/bug-view-43212.html
> fix: the ukcc's dispaly rotation is different from kds

- debian/control
- debian/rules
- shell/main.cpp
- shell/mainwindow.cpp
Desc: SW64架构下使用日志SDK或者加载电源管理模块均会导致段错误
Log: 1. 适配SW64架构；
2. SW64架构下不使用日志SDK且屏蔽电源管理模块
> Fix: crashed under SW64

- plugins/devices/shortcut/shortcut.cpp
log：【控制面板|快捷键】添加快捷键名称超出显示时省略，建议鼠标悬停在上面时增加悬停提示完整的名称
> Fix: bug54322 add tooltip for custom shortcut

- plugins/account/networkaccount/mainwidget.cpp
Description: translation:Kylin Cloud Account => 云账户
Log: 【云账户】云账户的通知信息，无个性化图标
Bug: http://172.17.66.192/biz/bug-view-40387.html
> Fix:bug #40387

- plugins/network/netconnect/netconnect.cpp
description: Mac address is incorrectly capitalized
log:物理地址大小写不正确
bug:53631  【cpm】【HUAWEI】【KOS】【WIFI】【功能测试】【L2】网络详情里面的Mac地址与打开终端输入命令查询的地址字段不一致 【一般+必现+不常用功能】
> fix(netconnect):mac address

- plugins/messages-task/search/search.cpp
Log: 修复黑名单文件夹路径显示不完整的问题，检查获取的黑名单列表是否是文件夹
PS: 本修改不影响控制面板功能，但与v10sp1 bug:http://pm.kylin.com/biz/bug-view-55034.html 联动，建议尽早上传，确定合入日期后我将通知搜索传包同事同步传包
> fix(search): Path of blocked folder is not complete & check values got from config file.

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/bluetoothmain.h
- plugins/devices/bluetooth/deviceinfoitem.cpp
Description: Eliminate Bluetooth devices that are not in range #bug:54436
Log: 控制面板显示蓝牙设备中，去除不在范围的蓝牙设备
> fix(bluetooth): 控制面板显示蓝牙设备中，去除不在范围的蓝牙设备

- plugins/account/userinfo/userinfo.cpp
- plugins/account/userinfo/userinfo.h
Bug#52246 【控制面板】国密算法对新建用户不生效
Bug#54057 【控制面板|账户信息】深色模式下，更改用户名图标未反白
> V10SP1 BUG Fix

- plugins/network/netconnect/netconnect.cpp
description:Fixed an empty display when not connected to a wired network
log:修复不连接有线网络，显示为空的问题
bug:56358
description:Fixed an issue where the connected network icon for dark themes was displayed incorrectly
log:修复深色主题已连接网络图标显示不正确的问题
bug:55336
> fix(netconnect):fix bug

- plugins/network/netconnect/netconnect.cpp
description:Fixed an empty display when not connected to a wired network
log:修复不连接有线网络，显示为空的问题
bug:56358
description:Fixed an issue where the connected network icon for dark themes was displayed incorrectly
log:修复深色主题已连接网络图标显示不正确的问题
bug:55336
> V10 fix(netconnect):fix bug

- plugins/network/netconnect/netconnect.cpp
description: Refresh the network to keep the page at the top
log: 刷新网络保持页面置顶
bug:55340
> V10 fix(netconnect):Refresh the network to keep the page at the top

- commonComponent/Uslider/uslider.cpp
- plugins/personalized/fonts/fonts.cpp
- plugins/personalized/fonts/fonts.ui
Description: Fonts Slider error
Log:  【控制面板|字体】字体设置栏16号字体右侧设计不合理
Bug: http://pm.kylin.com/biz/bug-view-52294.html
> fix(Fonts Slider): Fonts Slider

- commonComponent/Uslider/uslider.cpp
- plugins/personalized/fonts/fonts.cpp
- plugins/personalized/fonts/fonts.ui
Description:  Fonts Slider error
Log: 设置】字体调成11号放大窗口后字体被遮挡
Bug: http://pm.kylin.com/biz/bug-view-56036.html
> fix(Fonts Slider):  Fonts Slider

- plugins/network/netconnect/netconnect.cpp
description: The cable network is updated in real time when changes occur
log: 有线网络发生变化时进行实时更新
bug: 57130
> fix(netconnect): The cable network is updated in real time

- plugins/personalized/theme/theme.cpp
Description: Spacing is too large
Log: 控制面板|主题】主题恢复默认设置按钮位置不合理
Bug: http://pm.kylin.com/biz/bug-view-57533.html
> fix(ThemeUI): ThemeUI

- plugins/system/touchscreen/touchscreen.ui
Description：bug# 43407 【控制面板】触摸屏右侧边距需要调整和其他界面一致
Log：修改触摸屏右侧边距，从而与其他界面一致
Bug：http://pm.kylin.com/biz/bug-view-43407.html
> fix(touchscreen):fix bug #43407 

- plugins/system/display/widget.cpp
Description: 应用后点击恢复之前的配置。系统会恢复登录后的分辨率以及方向
Log:应用后点击恢复之前的配置。系统会恢复登录后的分辨率以及方向
Bug: http://pm.kylin.com/biz/bug-view-56579.html
> fix: update pre config when save monitor's config

- plugins/system/display/widget.cpp
Description: crashed by OutputPtr's empty pointer
Log: 双屏打开VGA显示器后开启统一输出崩溃
Bug: http://pm.kylin.com/biz/bug-view-57955.html
> fix: crashed by OutputPtr's empty pointer

- plugins/personalized/desktop/desktop.cpp
- plugins/personalized/desktop/desktop.h
Description: icon error
Log: 【控制面板|个性化-桌面】【有条件必然重现】个性化->主题->图标主题切换，桌面页签锁定在开始菜单的图标样式不会跟随切换。
Bug: http://pm.kylin.com/biz/bug-view-58168.html
> fix(Personalization-Desktop): Personalization-Desktop

- plugins/system/display/widget.cpp
Description: crashed by outputr's empty pointer
Log: 关闭hdmi显示器，插拔vga,打开hdmi闪退
Bug: http://pm.kylin.com/biz/bug-view-54390.html
> fix: crashed by outputr's empty pointer

- shell/searchwidget.cpp
Description: 在控制面板中可以索引到密码时效的信息并跳转，但实际没有该功能
Log: bug56558 && 53462
> fix(search): Shielding password effectiveness in search

- plugins/system/autoboot/autoboot.cpp
Description: Autoboot Switch env error
Log: 【控制面板】开机启动项添加成功，切换语言后，应用名称没有同步切换
Bug: http://pm.kylin.com/biz/bug-view-53819.html
> fix( Autoboot Switch env): Autoboot Switch env

- plugins/system/autoboot/addautoboot.cpp
- plugins/system/autoboot/addautoboot.h
Description:  There are duplicates
Log: 【控制面板】开机启动可以添加重复的搜索启动项
Bug: http://pm.kylin.com/biz/bug-view-57329.html
> fix(Autoboot): Autoboot

- plugins/devices/bluetooth/bluetoothmain.cpp
Fixed the problem of not being able to find my device label when powering on and restarting after hibernation after the first pairing
>  Fixed the problem of not being able to find my device label when powering on and restarting after hibernation after the first pairing

- plugins/system/autoboot/addautoboot.cpp
Description: Fix the problem of repeated applications
Log: 【控制面板】开机启动可以添加重复的搜索启动项
Bug: http://pm.kylin.com/biz/bug-view-57329.html
> fix(Autoboot):  Autoboot(fix)

- plugins/system/display/widget.cpp
Description: 笔记本调整亮度，快速拉动到暗笔记本黑屏无法恢复
Log: 亮度值最低为5
Bug: http://pm.kylin.com/biz/bug-view-54951.html
> fix(display): fix bug#54951

- plugins/system/power/power.cpp
Description: Power Setting
Log: cpm】【HUAWEI】【KOS】【电源管理】【V3】【L1】系统电源中“低电量执行操作”可设置1%-9%，实际3%电量时EC会下电关机，建议“低电量执行操作”设置区间为5%-9%。(提示+必现+常用功能)。
Bug: http://pm.kylin.com/biz/bug-view-59168.html
> fix(Power): Power

- plugins/account/networkaccount/mainwidget.cpp
Description: 显示错误
Log: 当同步项同步出错时，感叹号图标不会消失，除非重开。
Bug: 自测BUG
> Fix:Display error when item sync failed

- commonComponent/SwitchButton/switchbutton.cpp
Description: SwitchBtn question
Log: 【控制面板|通知】关闭设置通知来源中的“电源”的通知按钮时，不应该弹出子窗口
Bug: http://pm.kylin.com/biz/bug-view-59972.html
> fix(Notifycation): Notifycation

- plugins/devices/audio/ukmedia_main_widget.cpp
Fix:Adjust the input volume of the taskbar, the input volume value in the control panel does not change
Bug:59123
Description:调节任务栏输入音量的大小，控制面板中输入音量数值没有变化
> Fix:Adjust the input volume of the taskbar, the input volume value in the control panel does not change

- plugins/devices/audio/ukmedia_main_widget.cpp
Fix:Adjust the input volume of the taskbar, the input volume value in  the control panel does not change
Bug:59123
Description:调节任务栏输入音量的大小，控制面板中输入音量数值没有变化
> Fix:Adjust the input volume of the taskbar, the input volume value in  the control panel does not change

- plugins/account/networkaccount/maindialog.cpp
Description: 
解决如下两个BUG：
【cpm】【HUAWEI】【安全】【L1】【VN2整机】【KOS】【设置】云账户登录场景输入错误用户名，提示“用户不存在”(一般+必现+不常用功能)
【cpm】【HUAWEI】【安全】【L1】【VN2整机】【KOS】【设置】云账户登录场景，重复输入错误用户密码登录10次后，再登录提示“错误代码：656！”(一般+必现+不常用功能)
Log: 麻烦添加翻译：Too many failed attemps,please wait! ->登录错误次数过多，请五分钟后重试!
Bug: :#60840 #60837
> Fix:#bug 60840 #60837

- plugins/security-updates/upgrade/src/updatedbus.cpp
- plugins/security-updates/upgrade/src/updatedbus.h
修复bug#58211【系统更新】更新过程中，可以进行注销/重启/关机等操作
> Fix(Upgrade): file lock failed!

- plugins/messages-task/search/search.cpp
- shell/res/i18n/zh_CN.ts
修复#57455 翻译问题
#61923 家目录不是"/home”时无法屏蔽文件夹问题
> Fix(search):#57445 #61923 blocked folders can not be choosen when home path is not start with '/home'.

- plugins/system/display/widget.cpp
- plugins/time-language/datetime/datetime.cpp
Description: bug#62742:双屏】接入双屏后无法切换主屏
bug#62324:【设置|时间】当前用户与其他登录用户的时间设置不一致
Log: ret值未初始化导致返回值异常
同步状态调用dbus而不是gsetting
Bug: http://zentao.kylin.com/biz/bug-view-62742.html
http://zentao.kylin.com/biz/bug-view-62324.html
> fix(display and datetime): fix bugs

- plugins/account/networkaccount/mainwidget.cpp
bug:56671
Description: switch can not sync with real state 
Log: 修复开关会发生自动调整的问题
> Fix:bug #56671

- plugins/account/networkaccount/mainwidget.cpp
Description: switch can not sync with real state
Log: 修复开关会发生自动调整的问题
> Fix:Switch can not sync with real state

- plugins/account/networkaccount/mainwidget.cpp
Description: switch can not sync with real state
Log: 修复开关会发生自动调整的问题
> Fix(cloud accout):switch can not sync with real state

- shell/res/i18n/zh_CN.ts
Description: Change translation
Log: 【控制面板|网络】点击代理，手动设置代理中提示符号实际为中文分号
Bug: http://zentao.kylin.com/biz/bug-view-61919.html
> fix(Proxy): Proxy

- shell/utils/functionselect.cpp
Description: change homepage display
Log: 【系统设置】16号字体下的系统设置的开机启动显示不全
Bug: http://zentao.kylin.com/biz/bug-view-63004.html
> fix(Homepage UI): Homepage UI

- plugins/messages-task/about/about.cpp
- plugins/messages-task/about/about.ui
- shell/res/i18n/zh_CN.ts
Description: change button content
Log: 【系统授权】激活过期后按钮仍为“激活”非“延长服务”
Bug: http://zentao.kylin.com/biz/bug-view-54544.html
> fix(About UI): About UI

- plugins/system/display/controlpanel.cpp
- plugins/system/display/controlpanel.h
Description: plug and unplug the information display information error
Log: 接入4K外显，显示面板未同步更新4K外显信息
Bug: http://zentao.tjsource.xyz/biz/bug-view-62568.html
> fix: plug and unplug the information display information error

- plugins/system/defaultapp/defaultapp.cpp
Description: Increase audio format
Log: 【默认应用】将音频播放器默认应用更改为麒麟影音，双击.mmf格式音频文件依旧通过音乐播放器打开
Bug: https://zentao.kylin.com/biz/bug-view-62012.html
> fix(Default): Default

- shell/res/i18n/zh_CN.ts
Description: Fix  Translation
Log:  【云账户】云账户同步列表中未显示最新应用名   【控制面板|显示】更改分辨率/方向后的提示语中缺少“秒”字
Bug: https://zentao.kylin.com/biz/bug-view-61876.html  https://zentao.kylin.com/biz/bug-view-63035.html
> fix(Fix  Translation): Fix  Translation

- plugins/devices/bluetooth/bluetoothnamelabel.cpp
Description: Fix bluetooth
Log: 【控制面板|蓝牙】双击蓝牙名称后删除，蓝牙名称框显示空白
Bug: http://172.17.66.192/biz/bug-view-62832.html
>     fix(bluetooth): bluetooth

- plugins/system/display/outputconfig.cpp
- plugins/system/display/outputconfig.h
Description: 打开显示模块，切换分辨率为a，点击恢复之前配置。刷新率处显示为空。此时点击刷新率，刷新率显示的是a分辨率下的刷新率列表。此时如果点击任意刷新率，会切换到分辨率a
Log: 点击恢复，触发当前显示ID变化时，刷新率下拉框重新填充
Bug: http://zentao.kylin.com/biz/bug-view-62995.html
> fix(display): fix bug#62995

- shell/mainwindow.cpp
Description: The first level navigation is not fully displayed
Log: 【系统设置】当系统字体为16且为英文系统时，系统设置里的‘个性化’的英文显示不全
Bug: https://zentao.kylin.com/biz/bug-view-60426.html
> fix(First level navigation): First level navigation

- plugins/system/display/outputconfig.cpp
- plugins/system/display/outputconfig.h
- plugins/system/display/widget.cpp
- shell/mainwindow.cpp
- shell/res/i18n/bo.ts
- shell/res/i18n/en_US.ts
- shell/res/i18n/tr.ts
- shell/res/i18n/zh_CN.ts
Description: bug#62995,【控制面板】【显示】打开显示模块，切换分辨率为a，点击恢复之前配置。刷新率处显示为空。此时点击刷新率，刷新率显示的是a分辨率下的刷新率列表。此时如果点击任意刷新率，会切换到分辨率a
Log: 点击恢复，触发当前显示ID变化时，刷新率下拉框重新填充
Bug: http://zentao.kylin.com/biz/bug-view-62995.html
> fix(display): fix bug

- shell/res/i18n/zh_CN.ts
Description: Translation Error
Log: 【110104】【系统设置】显示器的提示框按钮不正确
Bug: http://zentao.kylin.com/biz/bug-view-62667.html
> fix(DisPlay):  DisPlay

- plugins/devices/bluetooth/bluetoothmain.cpp
log:63000【蓝牙】已连接过的蓝牙鼠标，再次连接时需要重新点击连接，列表中显示2个重复名称
62832【控制面板|蓝牙】双击蓝牙名称后删除，蓝牙名称框显示空白
44761【蓝牙】连接上蓝牙耳机后休眠，关闭蓝牙，再打开蓝牙，连接上耳机，控制面板中我的设备没有显示，任务栏有显示
62724【蓝牙】【用例86978】蓝牙文件接收过程中取消，多次弹出确认窗口
> 	fix:repair bug

- plugins/devices/bluetooth/bluetoothmain.cpp
Description : BUG#62068
Log : 执行sudo systemctl restart bluetooth.service命令重启蓝牙服务两次，控制面本版崩溃
> feat(Bluetooth) : Fixed Bug

- changeUserPwd/main.cpp
-衍生改动：pam密码校验与passwd密码校验走不同的锁定逻辑，当解锁时间不同时控制面板未对异常进行处理导致卡死，完善该逻辑
> 53692 【cpm】【HUAWEI】【KOS】【安全】【V3】【L1】连续多次输入错误的旧口令，系统没有采用任何保护措施用于防暴力破解

- debian/control
>  65531 【任务-控制面板-41834】添加依赖ddcutil，使得HDMI亮度调节可以使用

- plugins/system/display/outputconfig.cpp
- plugins/system/display/outputconfig.h
bug: 49942 【控制面板|显示器】修改刷新率，点击恢复之前设置失败
> fix(display)

- plugins/devices/touchpad/touchpad.cpp
Description: Fix Touchpad Question
Log: 【控制面板|触摸板】设置插入鼠标时候禁用触摸板不生效
Bug: http://172.17.66.192/biz/bug-view-67196.html
> fix(Touchpad): Touchpad

- plugins/system/display/widget.cpp
Description: 双屏模式下，控制面板显示器模块显示问题
Log: 显示器模块只显示一个
Bug: http://zentao.kylin.com/biz/bug-view-67493.html
> fix: unable to turn off unifed output

- plugins/system/display/outputconfig.cpp
Description: Display Error
Log: 【双屏】遍历设置-系统-显示器的设置，设置界面闪退
Bug:  http://172.17.66.192/biz/bug-view-67281.html
> fix(Display): Display

- plugins/system/display/widget.cpp
Description: 打开统一输出选项，应用后桌面图层错乱重叠，实际显示模式为扩展模式。(一般+低概率+常用功能)
Log: 打开统一输出选项，应用后桌面图层错乱重叠，实际显示模式为扩展模式。(一般+低概率+常用功能)
Bug: https://zentao.tjsource.xyz/biz/bug-view-62566.html
> fix: unified output problem

- plugins/security-updates/upgrade/src/tabwidget.cpp
【cpm】【HUAWEI】【KOS】【非用例】【VN2整机】系统还原，选择系统更新时生成的备份文件，出现“备份还原分区异常”的提示(一般+必现+不常用功能)
> update: fix bug#63240 

- plugins/system/display/declarative/qmlscreen.cpp
- plugins/system/display/widget.cpp
- plugins/system/display/widget.h
Description: 关闭第二显示器后打开控制面板显示模块错位
Log: 关闭第二显示器后打开控制面板显示模块错位
Bug: http://zentao.kylin.com/biz/bug-view-68442.html
> fix: overlapping problems

- plugins/system/display/unifiedoutputconfig.cpp
Description: Display Scale (Unified)
Log: 【cpm】【HUAWEI】【graphic】【OS】【L2】【PtoF】【V4】DUT接4K显示器，在2160*1440的镜像模式下可以切换至200%/175%的缩放比例，但单屏下该分辨率却不能。（必现+一般+不常用功能）
Bug: http://172.17.66.192/biz/bug-view-69326.html
> fix(Display Scale (Unified)): Display Scale (Unified)
