- plugins/account/userinfo/userinfo.cpp
click change type button to show change type dialog in userInfo page.
> click change type button to show change type dialog(#51)

- plugins/plugins.pro
temporary logout of touchpad module
> temporary logout of touchpad module

- shell/homepagewidget.cpp
- shell/homepagewidget.h
add a slot on the main page. Now when user click on the main page in logo or main title like "系统"， will open the detail page(#48).
> fix on the main page, click to open is invalid.

- shell/mainwindow.cpp
- shell/mainwindow.h
- shell/modulepagewidget.cpp
recordFuncStack can remember history steps.  I think it is better return to homepage when there is no history recoed rather than disable backBtn.
> when there is no history record, return to homepage.

- plugins/network/netconnect/netconnect.cpp
> Remove broken single quote

- data/org.ukui.control-center.panel.plugins.gschema.xml
- plugins/account/userinfo/createuserdialog.cpp
- plugins/account/userinfo/createuserdialog.h
- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
- plugins/time-language/area/area.cpp
- plugins/time-language/area/dataformat.cpp
- plugins/time-language/area/dataformat.h
- plugins/time-language/datetime/datetime.cpp
- plugins/time-language/datetime/datetime.h
- shell/homepagewidget.cpp
> fix issues

- plugins/system/display/outputconfig.cpp
- plugins/system/display/widget.cpp
Modify key value due to gsetting API error
> Modify key value due to gsetting API error

- debian/control
> Add dependency in Suggest

- debian/control
- plugins/system/display/widget.cpp
Change dependencies and hide night mode when redshift is not installed
> Change dependencies and hide night mode when redshift is not installed

- debian/control
- plugins/system/display/widget.cpp
add add dependency of [qml-module-qtquick-controls]
> add add dependency of [qml-module-qtquick-controls]

- plugins/account/userinfo/createuserdialog.cpp
* change the code of createuser, show "Inconsistency with pwd" only if fouce in Pwd Sure Lineedit
> change code logic of createuser@[hebing]

- plugins/personalized/wallpaper/wallpaper.cpp
- plugins/personalized/wallpaper/wallpaper.h
- plugins/personalized/wallpaper/wallpaper.ui
* add the function of brower local wp
> function for browerlocalwp btn @hebing

- data/org.ukui.control-center.notice.gschema.xml
- plugins/system/autoboot/addautoboot.cpp
- plugins/system/autoboot/addautoboot.ui
* revision the ui of add autoboot
> add autoboot revision @hebing

- debian/install
- registeredQDbus/registeredQDbus.pro
* do not install config file by debian/install, change to *.pro
> ukcc config install @hebing

- plugins/system/defaultapp/defaultapp.cpp
* Increased judgment in defaultapp function to avoid segment errors
> judge defaultapp @hebing

- debian/control
* add build depends for function of networkaccount
> add build deps @hebing

- plugins/devices/audio/audio.pro
- plugins/devices/audio/ukmedia_input_widget.cpp
- plugins/devices/audio/ukmedia_input_widget.h
- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_main_widget.h
- plugins/devices/audio/ukmedia_output_widget.cpp
- plugins/devices/audio/ukmedia_output_widget.h
- plugins/devices/audio/ukmedia_sound_effects_widget.cpp
- plugins/devices/audio/ukui_custom_style.cpp
- plugins/devices/audio/ukui_custom_style.h
Draw the color of the volume icon in the control panel according to the change of theme
>  Draw the color of the volume icon in the control panel according to the change of theme

- plugins/account/networkaccount/config_list_widget.cpp
- plugins/account/networkaccount/dialog_login_reg.cpp
- plugins/account/networkaccount/editpassdialog.cpp
- plugins/account/networkaccount/network_item.cpp
- plugins/account/networkaccount/network_item.h
- plugins/account/networkaccount/ql_swichbutton.cpp
- plugins/account/networkaccount/ql_swichbutton.h
1.Fixed the issue of Allocate crashed.
2.Fixed the issue of Auto-sync.
3.Fixed the issue of the font size of English version.
4.Fixed the issue of BindDialog.
5.Changed some part of  function 'CurrentIndex()' to 'CurrentWidget()'.
> fixed some issue

- plugins/devices/shortcut/addshortcutdialog.cpp
- plugins/devices/shortcut/addshortcutdialog.h
- plugins/devices/shortcut/addshortcutdialog.ui
* forbid create new shortcut if the input is null
> increase filter for create new Shortcut @hebing

- plugins/account/userinfo/changefacedialog.cpp
- plugins/account/userinfo/userinfo.cpp
* add default face in selected list and fix the face change delay
> add default face @hebing

- plugins/personalized/wallpaper/wallpaper.cpp
* fix the problem that no preview color wallpaper
> fix no preview color wp @smiley286

- plugins/devices/audio/ukmedia_input_widget.cpp
- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_output_widget.cpp
Adapt to 4K screen and fixed occasionally triggering to obtain input level when modifying volume
>   Adapt to 4K screen and  fixed occasionally triggering to obtain input level when modifying volume 

- plugins/devices/shortcut/customlineedit.cpp
- plugins/devices/shortcut/customlineedit.h
- plugins/devices/shortcut/defineshortcutitem.cpp
- plugins/devices/shortcut/shortcut.cpp
* fix crash when add new shortcut accidental
> fix crash when add new shortcut accidental @smiley286

- shell/homepagewidget.cpp
* no switch when module has no functions
> no switch when module has no functions @smiley286

- plugins/devices/audio/ukmedia_main_widget.cpp
Set the initial state of the switch music
> Set the initial state of the switch music

- plugins/devices/mouse/mousecontrol.cpp
- plugins/devices/touchpad/touchpad.cpp
- shell/mainwindow.cpp
* add judge for mouse, touchpad, screenlock
> add judge for mouse,touchpad,screenlock @smiley

- plugins/account/networkaccount/bindphonedialog.cpp
- plugins/account/networkaccount/bindphonedialog.h
- plugins/account/networkaccount/config_list_widget.cpp
- plugins/account/networkaccount/config_list_widget.h
- plugins/account/networkaccount/dbushandleclient.cpp
- plugins/account/networkaccount/dbushandleclient.h
- plugins/account/networkaccount/dialog_login_reg.cpp
- plugins/account/networkaccount/dialog_login_reg.h
- plugins/account/networkaccount/editpassdialog.cpp
- plugins/account/networkaccount/editpassdialog.h
- plugins/account/networkaccount/logindialog.cpp
- plugins/account/networkaccount/networkaccount.cpp
- plugins/account/networkaccount/networkaccount.pro
- plugins/account/networkaccount/passdialog.cpp
- plugins/account/networkaccount/ql_combobobx.cpp
- plugins/account/networkaccount/ql_lineedit_pass.cpp
- plugins/account/networkaccount/ql_swichbutton.cpp
- plugins/account/networkaccount/qtooltips.cpp
- plugins/account/networkaccount/regdialog.cpp
fixed edit dialog's issue
fixed signal problem
adjust UI
fixed leak memory
> add dbus support

- plugins/account/userinfo/changetypedialog.cpp
- plugins/account/userinfo/changetypedialog.h
- plugins/account/userinfo/userinfo.cpp
* forbiden change account type to standard when admin num is the last one
> adjust for admin num @smiley286

- plugins/devices/audio/audio.pro
- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/plugins.pro
Fix sound module compilation error in v10
> Fix sound module compilation error in v10

- plugins/devices/shortcut/showallshortcut.cpp
- plugins/personalized/theme/theme.cpp
- plugins/system/display/widget.cpp
Signed-off-by: Z-bin <b20150304221@stu.ccsu.edu.cn>
> Adapt Qt 5.6 for night mode and theme

- plugins/devices/shortcut/shortcut.cpp
- plugins/devices/shortcut/shortcut.h
- plugins/network/proxy/proxy.cpp
- plugins/network/proxy/proxy.h
- plugins/personalized/fonts/fonts.cpp
- plugins/system/autoboot/autoboot.cpp
- shell/utils/functionselect.h
* rm QObjectUserData in shell/ and replace setUserData with setProperty
> rm QObjectUserData & replace setUserData @smiley286

- commonComponent/SwitchButton/switchbutton.cpp
- plugins/account/userinfo/userinfo.cpp
- plugins/devices/keyboard/keyboardcontrol.cpp
- plugins/devices/keyboard/keyboardcontrol.h
- plugins/devices/keyboard/keyboardcontrol.ui
- plugins/devices/printer/printer.cpp
- plugins/devices/printer/printer.h
- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
- plugins/network/vpn/vpn.cpp
- plugins/network/vpn/vpn.h
- plugins/network/vpn/vpn.ui
- plugins/personalized/fonts/fonts.cpp
- plugins/personalized/fonts/fonts.h
- plugins/personalized/fonts/fonts.pro
- plugins/personalized/fonts/fonts.ui
- plugins/personalized/screenlock/screenlock.cpp
- plugins/personalized/screenlock/screenlock.h
- plugins/personalized/screensaver/screensaver.cpp
- plugins/personalized/theme/theme.cpp
- plugins/personalized/theme/themewidget.cpp
- plugins/system/autoboot/autoboot.cpp
- plugins/system/autoboot/autoboot.h
- plugins/time-language/area/area.cpp
- shell/main.cpp
- shell/mainwindow.cpp
- shell/mainwindow.h
- shell/ukui-control-center.desktop
- shell/utils/functionselect.cpp
1:Reduce the modules displayed on the homepage to avoid incomplete text display
2:Fix issue ukui#310
3:Change the add button to the entire background bar and click
> Change switchbutton style

- plugins/account/networkaccount/area_code_lineedit.cpp
- plugins/account/networkaccount/area_code_lineedit.h
- plugins/account/networkaccount/bindphonedialog.cpp
- plugins/account/networkaccount/config_list_widget.cpp
- plugins/account/networkaccount/dbushandleclient.cpp
- plugins/account/networkaccount/item_list.cpp
- plugins/account/networkaccount/logindialog.cpp
- plugins/account/networkaccount/mcode_widget.cpp
- plugins/account/networkaccount/mcode_widget.h
- plugins/account/networkaccount/network_item.cpp
- plugins/account/networkaccount/passdialog.cpp
- plugins/account/networkaccount/ql_box_item.cpp
- plugins/account/networkaccount/ql_combobobx.cpp
- plugins/account/networkaccount/ql_lineedit_pass.cpp
- plugins/account/networkaccount/ql_popup.cpp
- plugins/account/networkaccount/ql_pushbutton_edit.cpp
- plugins/account/networkaccount/ql_swichbutton.cpp
- plugins/account/networkaccount/ql_swichbutton.h
- plugins/account/networkaccount/qtooltips.cpp
- plugins/account/networkaccount/regdialog.cpp
- plugins/account/networkaccount/successdiaolog.cpp
1.fixed issue #345
2.add comment for per cpp file
> fixed issue #345

- plugins/personalized/screensaver/screensaver.cpp
- plugins/personalized/screensaver/screensaver.h
* fix crash in sscreensaver when user upgrade system from old
> fix crash in screensaver @smiley286

- plugins/system/autoboot/addautoboot.cpp
- plugins/system/autoboot/addautoboot.h
- plugins/system/autoboot/autoboot.cpp
* fix bug, the btn of add autoboot do not work
> fix add autoboot invaild @smiley286

- plugins/account/networkaccount/config_list_widget.cpp
> fixed some logical problem

- plugins/personalized/desktop/desktop.cpp
shield blueman-applet in plugin-desktop
>  shield blueman-applet in plugin-desktop

- plugins/devices/mouse/mousecontrol.cpp
- plugins/devices/mouse/mousecontrol.h
* code function of cursor blink
> add function of cursor blink @smiley286

- plugins/personalized/theme/themewidget.cpp
* selected icon change png to svg, but not update the code
> update selected icon in theme @smiley286

- plugins/devices/printer/printer.cpp
- plugins/devices/printer/printer.h
* update printer dev per 1second
> update printer dev auto @smiley286

- plugins/devices/keyboard/kbdlayoutmanager.cpp
* do not add TW in selecte list
> deal TW in keyboard layout @smiley286

- plugins/devices/audio/audio.pro
- plugins/devices/audio/customstyle.cpp
- plugins/devices/audio/customstyle.h
- plugins/devices/audio/switchbutton.cpp
- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_output_widget.cpp
- plugins/devices/audio/ukmedia_output_widget.h
- plugins/devices/audio/ukmedia_slider_tip_label_helper.cpp
- plugins/devices/audio/ukmedia_slider_tip_label_helper.h
- plugins/devices/audio/ukmedia_sound_effects_widget.cpp
- plugins/devices/audio/ukui_custom_style.cpp
- plugins/devices/audio/ukui_custom_style.h
Modify the window spacing, add a prompt label for the channel balance slider
> Modify ui detail style

- plugins/system/defaultapp/defaultapp.cpp
* add html type to default open when set default browser app
> fix default browser invalid @smiley286

- plugins/system/autoboot/autoboot.cpp
* change label text from base name to name in autostart
> change label text in autostart @smiley286

- plugins/personalized/screensaver/screensaver.cpp
* change signal of slider let click valid
> change signal of slider in screensaver @smiley286

- plugins/devices/shortcut/addshortcutdialog.cpp
- plugins/devices/shortcut/showallshortcut.cpp
* fix segfault by change QIcon
> fix the segfault when close ukcc on ukui3.0 for XX @smiley286

- plugins/personalized/screenlock/screenlock.cpp
* screenlock delay is invalid, hide component
> hide screenlock delay settings @smiley286

- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/changepwddialog.h
- plugins/account/userinfo/changepwddialog.ui
- plugins/account/userinfo/createuserdialog.cpp
- plugins/account/userinfo/createuserdialog.h
- plugins/account/userinfo/createuserdialog.ui
- plugins/account/userinfo/userinfo.cpp
- plugins/account/userinfo/userinfo.h
* add passwd check for change pwd and creat user
> support pwquality @smiley286

- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_main_widget.h
- plugins/devices/audio/ukmedia_sound_effects_widget.cpp
- plugins/devices/audio/ukmedia_sound_effects_widget.h
Signed-off-by: fzx-h <fengzhaoxiang@kylinos.cn>
> Add a switch to control the sound

- data/org.ukui.control-center.keyboard.gschema.xml
- plugins/devices/keyboard/keyboardcontrol.cpp
- plugins/devices/keyboard/keyboardcontrol.h
- plugins/devices/keyboard/keyboardcontrol.ui
- shell/shell.pro
add tip of keyboard pressed; add reset settings of keyboard layouts
> Addfunc1.dev

- plugins/devices/mouse/mouse.pro
- plugins/devices/mouse/mousecontrol.cpp
- plugins/devices/mouse/mousecontrol.h
- plugins/devices/mouse/mousecontrol.ui
* add mouse mid btn speed setting
> add function of mouse mid btn setting @smiley286

- plugins/devices/mouse/mousecontrol.cpp
- plugins/devices/mouse/mousecontrol.ui
* add cursor blink speed settings
> add cursor blink speed settings @smiley286

- plugins/system/power/power.cpp
- plugins/system/power/power.h
- plugins/system/power/power.ui
- plugins/system/power/powermacrodata.h
* add close lid
* add "charge" option for icon policy
* add darken when idle
> add new feature for power @smiley286

- plugins/account/userinfo/changevailddialog.cpp
- plugins/account/userinfo/changevailddialog.h
- plugins/account/userinfo/changevailddialog.ui
- plugins/account/userinfo/userinfo.cpp
- plugins/account/userinfo/userinfo.h
- plugins/account/userinfo/userinfo.pro
- plugins/account/userinfo/userinfo.ui
* add function of pwd valid settings in user
> add function of pwd valid settings

- .github/workflows/build.yml
- plugins/system/display/displayperformancedialog.cpp
* Daily auto check
* Check build on Debian
* Check build on Fedora
* Check build on Archlinux
Fedora needs to wait for a patch update.
> Support check build on multi distros

- plugins/network/netconnect/netconnect.cpp
- plugins/system/display/widget.cpp
- plugins/system/display/widget.h
Signed-off-by: Z-bin <1134636325@qq.com>
> Solve the problem of setting screen orientation black screen in Qt5.6

- plugins/account/userinfo/changevailddialog.cpp
* user pwd valid not init when status is Nerver
> fix user pwd valid not init @smiley286

- plugins/devices/shortcut/customlineedit.cpp
- plugins/devices/shortcut/getshortcutworker.cpp
- plugins/devices/shortcut/shortcut.cpp
* fix desktop shortcut not show and editline not reset when ESC pressed
> fix desktop shortcut not show @smiley286

- plugins/system/power/power.cpp
- plugins/system/power/power.h
- plugins/system/power/power.pro
> Fix bug Desktop can be set with battery supply

- plugins/system/display/displayperformancedialog.cpp
- plugins/system/display/displayperformancedialog.h
- plugins/system/display/displayperformancedialog.ui
- plugins/system/display/widget.cpp
> connect to kylin-wm-chooser @smiley286

- plugins/account/userinfo/createuserdialog.cpp
- plugins/account/userinfo/createuserdialog.h
* recode to the username check when create new user
> recode to the username check @smiley286

- plugins/devices/keyboard/kbdlayoutmanager.cpp
- plugins/devices/keyboard/kbdlayoutmanager.h
- plugins/devices/keyboard/keyboard.pro
- plugins/devices/keyboard/keyboardcontrol.cpp
- plugins/devices/keyboard/layoutmanager.ui
* recode keyboard layout manager with new ui
> recode keyboard layout manager @smiley286

- plugins/devices/shortcut/shortcut.cpp
- plugins/devices/shortcut/showallshortcut.cpp
- plugins/devices/shortcut/showallshortcut.h
* i18n the key in showallshortcut
> i18n the key in showallshortcut @smiley286

- plugins/account/networkaccount/maindialog.cpp
> add returned key to login support

- plugins/devices/keyboard/kbdlayoutmanager.cpp
- plugins/devices/keyboard/layoutmanager.ui
- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.ui
- plugins/personalized/screensaver/screensaver.cpp
- plugins/personalized/screensaver/screensaver.ui
- plugins/system/defaultapp/defaultapp.cpp
- plugins/system/display/resolutionslider.cpp
- plugins/system/display/widget.cpp
> Fix issue #548

- plugins/account/userinfo/changevailddialog.ui
- plugins/account/userinfo/userinfo.ui
- plugins/personalized/screenlock/screenlock.cpp
- plugins/personalized/screensaver/screensaver.cpp
- plugins/personalized/screensaver/screensaver.h
- plugins/system/display/displayperformancedialog.ui
- plugins/system/power/power.ui
- tastenbrett/tastenbrett.pro
>  Adjust the installation path of tastenbrett

- plugins/devices/audio/ukmedia_output_widget.cpp
Solve segfault in open control panel
> Solve segfault in open control panel

- plugins/personalized/wallpaper/colordialog.cpp
- plugins/personalized/wallpaper/colordialog.h
- plugins/personalized/wallpaper/colordialog.ui
- plugins/personalized/wallpaper/colorpreview.cpp
- plugins/personalized/wallpaper/colorpreview.h
- plugins/personalized/wallpaper/colorsquare.cpp
- plugins/personalized/wallpaper/colorsquare.h
- plugins/personalized/wallpaper/gradientslider.cpp
- plugins/personalized/wallpaper/gradientslider.h
- plugins/personalized/wallpaper/wallpaper.cpp
- plugins/personalized/wallpaper/wallpaper.h
- plugins/personalized/wallpaper/wallpaper.pro
> Add custom colordialog

- plugins/devices/audio/ukmedia_input_widget.cpp
- plugins/devices/audio/ukmedia_input_widget.h
- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_main_widget.h
- plugins/devices/audio/ukmedia_output_widget.cpp
- plugins/devices/audio/ukmedia_output_widget.h
solve the problem of no sound when open the control panel
> solve the problem of no sound when open the control panel

- plugins/devices/shortcut/shortcut.cpp
- plugins/personalized/wallpaper/wallpaper.cpp
- plugins/personalized/wallpaper/wallpaper.ui
> fix: reset shortcut,show all shortcut no update

- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
Remove the unused QTimer in right time.
> Fixed issue of Login dialog

- plugins/plugins.pro
- plugins/system/autoboot/autoboot.cpp
* the reason of error is unknown, change copy function from glib to qt
> fix autostart invalid checked first time @smiley

- plugins/devices/shortcut/customlineedit.cpp
- plugins/devices/shortcut/customlineedit.h
- plugins/devices/shortcut/defineshortcutitem.cpp
- plugins/devices/shortcut/shortcut.cpp
> fix shortcut

- plugins/personalized/theme/theme.cpp
- plugins/personalized/theme/theme.h
plugins/personalized/theme/theme.h
> change singel step of transparency sliderbar

- plugins/devices/shortcut/shortcut.cpp
> fix shortcut: qstring to char

- plugins/personalized/desktop/desktop.cpp
kylin-nm & ukui-volume-control-applet-qt clicked error in panel-storage  #15840
> kylin-nm & ukui-volume-control-applet-qt clicked error in panel-storage  #15840

- plugins/personalized/wallpaper/wallpaper.cpp
- plugins/personalized/wallpaper/wallpaper.h
- plugins/personalized/wallpaper/wallpaper.ui
Separate the wallpaper placement combox from the wallpaper type combox.
As the function of setting wallpaper placement mode has not been implemented, its combo box is temporarily hidden.
> Split the wallpaper combox.

- plugins/devices/shortcut/addshortcutdialog.cpp
* annotate the code that set ok to select
> annotate select in add shortcut page @smiley286

- plugins/personalized/fonts/fonts.ui
Repair the distance between blocks
>  Repair the distance between blocks #544

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
- plugins/network/netconnect/netconnect.ui
When adding or deleting networks, changing network properties or changing network connections, the list of available networks will be updated synchronously.
网络--网络连接--当增删网络连接，更改当前网络连接状态，更改可用网络属性时，同步更新可用网络列表
> Refresh the list of available networks synchronously.

- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/createuserdialog.cpp
- plugins/account/userinfo/passwdcheckutil.cpp
- plugins/account/userinfo/passwdcheckutil.h
- plugins/account/userinfo/userinfo.cpp
- plugins/account/userinfo/userinfo.pro
> add check for pwquality @smiley286

- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/changepwddialog.ui
Adjust the layout for changing-user-password dialog according to design draft.
> Adjust the changing-user-password dialog layout.

- plugins/account/userinfo/userinfo.cpp
- plugins/devices/shortcut/shortcut.cpp
- plugins/messages-task/notice/notice.cpp
Fix ui bugs for shortcuts and notice for master version.
> Fix ui bugs for shortcuts and notice for master version

- plugins/devices/shortcut/shortcut.cpp
- plugins/devices/shortcut/shortcut.h
> fix custom shortcut can not delete

- plugins/devices/shortcut/addshortcutdialog.ui
- plugins/devices/shortcut/customlineedit.cpp
- plugins/devices/shortcut/defineshortcutitem.cpp
- plugins/devices/shortcut/defineshortcutitem.h
- plugins/devices/shortcut/shortcut.cpp
- shell/res/i18n/bo.ts
- shell/res/i18n/tr.ts
- shell/res/i18n/zh_CN.ts
> fix custom shortcut ui

- plugins/account/userinfo/createuserdialog.cpp
- plugins/account/userinfo/userinfo.cpp
- plugins/account/userinfo/userinfo.ui
- shell/component/leftwidgetitem.cpp
- shell/mainwindow.cpp
- shell/mainwindow.ui
- shell/modulepagewidget.cpp
- shell/modulepagewidget.ui
- shell/res/i18n/zh_CN.ts
> Changed the UI of the interface

- plugins/account/userinfo/changegroupdialog.cpp
- plugins/account/userinfo/changegroupdialog.h
- plugins/account/userinfo/changegroupdialog.ui
- plugins/account/userinfo/creategroupdialog.h
- plugins/account/userinfo/definegroupitem.cpp
- plugins/account/userinfo/definegroupitem.h
- plugins/account/userinfo/delgroupdialog.cpp
- plugins/account/userinfo/delgroupdialog.ui
- plugins/account/userinfo/editgroupdialog.cpp
- plugins/account/userinfo/editgroupdialog.h
- plugins/account/userinfo/editgroupdialog.ui
- plugins/account/userinfo/userinfo.pro
- shell/res/i18n/bo.ts
- shell/res/i18n/en_US.ts
- shell/res/i18n/tr.ts
- shell/res/i18n/zh_CN.ts
> Optimization logic && Perfect func

- plugins/devices/shortcut/shortcut.cpp
- plugins/devices/shortcut/shortcut.h
- plugins/devices/shortcut/shortcut.pro
> add listen to cloud service

- plugins/account/userinfo/changefacedialog.cpp
- plugins/account/userinfo/changefacedialog.ui
> Fix:SystemRun do not support Chinese command.

- plugins/personalized/wallpaper/colordialog.cpp
- plugins/personalized/wallpaper/colordialog.ui
> add custom colorsquare radius

- plugins/account/networkaccount/mainwidget.cpp
- shell/res/i18n/zh_CN.ts
> Adjust Ui for Cloud Account

- plugins/account/userinfo/changefacedialog.ui
- plugins/account/userinfo/changepwddialog.ui
- plugins/account/userinfo/changetypedialog.ui
- plugins/account/userinfo/createuserdialog.ui
把用户信息弹窗的titlebar由QWidget类型转换为QFrame:box，以得到设计稿要求的标题栏样式。
> Adjust UI for userinfo dialog.

- shell/border_shadow_effect.cpp
- shell/border_shadow_effect.h
- shell/component/leftwidgetitem.cpp
- shell/mainwindow.cpp
- shell/mainwindow.h
- shell/modulepagewidget.cpp
- shell/shell.pro
> Add ground-glass effects and adjust parts of the UI

- plugins/account/userinfo/userinfo.cpp
- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.ui
- plugins/security-updates/update/update.ui
- plugins/system/autoboot/autoboot.cpp
- plugins/system/defaultapp/defaultapp.cpp
- plugins/system/display/display.ui
- plugins/system/power/power.ui
- shell/modulepagewidget.cpp
- shell/res/i18n/bo.ts
- shell/res/i18n/en_US.ts
- shell/res/i18n/tr.ts
- shell/res/i18n/zh_CN.ts
- shell/utils/functionselect.cpp
> Fix sinicization of time bar && Grammatical errors

- plugins/devices/shortcut/shortcut.cpp
> Add: update shortcut when cloud service signal is received

- shell/border_shadow_effect.cpp
- shell/border_shadow_effect.h
- shell/component/leftwidgetitem.cpp
- shell/mainwindow.cpp
> Solve the BUG that the rounded corners still exist after zooming in, and solve the BUG of dragging window

- plugins/personalized/wallpaper/wallpaper.h
> Fix the problem that the wallpaper module cannot be loaded

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
- plugins/network/netconnect/netconnect.ui
- shell/res/plugins/netconnect/addnet.svg
- shell/res/plugins/netconnect/wifi1.svg
- shell/res/plugins/netconnect/wifi2.svg
- shell/res/plugins/netconnect/wifi4.svg
- shell/res/plugins/netconnect/wifi5.svg
- shell/res/resfile.qrc
根据蓝湖设计稿调整网络连接的界面布局，修复网络列表wifi强度对应图标有误的问题。
> Adjust layout for netconnect.

- plugins/account/userinfo/changevaliddialog.ui
> pos of month and day in confusion at user pwd valid function @smiley

- plugins/account/userinfo/changegroupdialog.cpp
- plugins/system/autoboot/addautoboot.cpp
- shell/res/i18n/bo.ts
- shell/res/i18n/en_US.ts
- shell/res/i18n/tr.ts
- shell/res/i18n/zh_CN.ts
Link: http://pm.kylin.com/biz/bug-view-17016.html
> Fix: Autoboot ui Sinicization

- shell/modulepagewidget.cpp
Link: http://pm.kylin.com/biz/bug-view-17811.html
Link: http://pm.kylin.com/biz/bug-view-18094.html
> Fix: hover listwidget

- plugins/security-updates/securitycenter/securitycenter.cpp
- shell/modulepagewidget.cpp
- shell/res/i18n/bo.ts
- shell/res/i18n/en_US.ts
- shell/res/i18n/tr.ts
- shell/res/i18n/zh_CN.ts
- shell/utils/functionselect.cpp
Link: http://pm.kylin.com/biz/bug-view-17812.html
> Fix: bug word format

- plugins/account/userinfo/userinfo.cpp
- plugins/devices/shortcut/showallshortcut.cpp
修复删除用户不授权导致删除失败时，用户列表会把该用户隐藏的bug。
修复查看全部快捷键的弹窗出现不必要的横向滚动条的bug。
> Fix: user item will be hide when deleting user failed.

- plugins/account/userinfo/changevaliddialog.cpp
- plugins/time-language/datetime/changtime.cpp
* change i18n with requirement
> change i18n @smiley286

- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_main_widget.h
- plugins/devices/audio/ukmedia_output_widget.cpp
Feature: Add the ablity to switch configuration files
> Feature: Add the ablity to switch configuration files

- plugins/system/power/power.cpp
> fix idle dark settings @smiley286

- plugins/devices/shortcut/getshortcutworker.cpp
Link: http://pm.kylin.com/biz/bug-view-17762.html
Link: http://pm.kylin.com/biz/bug-view-18037.html
> Fix: do not show xfree86 shortcut

- plugins/devices/keyboard/kbdlayoutmanager.cpp
- plugins/devices/keyboard/kbdlayoutmanager.h
- plugins/devices/printer/printer.cpp
> not allow add same layout @smiley

- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/createuserdialog.cpp
- plugins/account/userinfo/userinfo.cpp
* pwd can not contain chinese
* the last adm can not been del
> pwd bug fix @smiley

- debian/control
- plugins/personalized/wallpaper/wallpaper.cpp
Link: http://pm.kylin.com/biz/bug-view-19023.html
> Fix: fail to set TIF format wallpaper

- plugins/system/autoboot/addautoboot.cpp
* invalid when reselect a desktop in add autostart
> fix bug#20482 @smiley286

- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/createuserdialog.cpp
- shell/res/i18n/bo.ts
- shell/res/i18n/en_US.ts
- shell/res/i18n/tr.ts
- shell/res/i18n/zh_CN.ts
修复：纯数字密码可以创建用户的BUG。
Link:http://172.17.66.192/biz/bug-view-19187.html
> Fix: new account can be created when password is too simple.

- shell/mainwindow.cpp
* 增加三权分立的判断，开启条件shell.pro中增加DEFINES += WITHKYSEC
> Fix BUG# 20417 没有根据三权分立定制不同的选项

- checkUserPwd/checkUserPwd.pro
- checkUserPwd/main.cpp
- debian/ukui-control-center.postinst
- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/changepwddialog.h
- plugins/account/userinfo/changepwddialog.ui
- plugins/account/userinfo/createuserdialog.cpp
- plugins/account/userinfo/createuserdialog.h
- plugins/account/userinfo/run-passwd.cpp
- plugins/account/userinfo/run-passwd.h
- plugins/account/userinfo/userinfo.cpp
- plugins/account/userinfo/userinfo.pro
- ukui-control-center.pro
* add current pwd check for all user
> Add Current Pwd Check @smiley286

- plugins/devices/audio/ukmedia_main_widget.cpp
Fix:Solve the problem that the sound disappears abnormally when opening the control panel when using wired headphones
Link:http://172.17.66.192/biz/bug-view-21413.html
> Fix:Solve the problem that the sound disappears abnormally when opening the control panel when using wired headphones

- plugins/account/userinfo/changegroupdialog.cpp
- plugins/account/userinfo/creategroupdialog.cpp
- plugins/account/userinfo/delgroupdialog.cpp
- plugins/account/userinfo/editgroupdialog.cpp
- shell/res/i18n/bo.ts
- shell/res/i18n/en_US.ts
- shell/res/i18n/tr.ts
- shell/res/i18n/zh_CN.ts
Link: http://pm.kylin.com/biz/bug-view-21836.html
Link: http://pm.kylin.com/biz/bug-view-21833.html
Link: http://pm.kylin.com/biz/bug-view-21752.html
Link: http://pm.kylin.com/biz/bug-view-21593.html
> Fix: crash after editing group id && update translation

- plugins/devices/audio/ukmedia_main_widget.cpp
Solve the problem that the sound card and the configuration file do not change together
> Solve the problem that the sound card and the configuration file do not change together

- plugins/devices/audio/ukmedia_input_widget.cpp
- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_output_widget.cpp
Remove redundant input devices
> Remove redundant input devices

- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/changepwddialog.h
- plugins/account/userinfo/userinfo.cpp
* can not change pwd type under root
> fix BUG#20443 function invalid under root

- plugins/account/userinfo/changegroupdialog.cpp
- plugins/account/userinfo/creategroupdialog.cpp
- plugins/account/userinfo/delgroupdialog.cpp
- plugins/account/userinfo/editgroupdialog.cpp
- shell/res/i18n/en_US.ts
- shell/res/i18n/zh_CN.ts
> Fix: Increase restrictions on deleting groups && update translation

- debian/control
> Fix: Unable to delete custom shortcut key

- plugins/devices/audio/ukmedia_main_widget.cpp
Solve the problem of incorrect output port when manually modifying the configuration file
> Solve the problem of incorrect output port when manually modifying the configuration file

- .github/workflows/build.yml
- debian/control
- group-manager-server/conf/org.ukui.groupmanager.policy
- group-manager-server/group-manager-server.pro
- plugins/account/userinfo/changegroupdialog.cpp
- plugins/account/userinfo/changegroupdialog.h
- plugins/account/userinfo/userinfo.pro
> Add: polkit of group

- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/changevaliddialog.cpp
Description: 密码检测中的参数增加引号，防止用户使用引号作为密码后检测失败
Description：密码过期时间从当前时间+1day开始
>    Fix(userinfo):

- plugins/account/userinfo/changegroupdialog.cpp
- shell/res/i18n/en_US.ts
- shell/res/i18n/zh_CN.ts
> Add: User group window title

- plugins/account/networkaccount/itemlist.h
- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
> Fix: bug #22592

- plugins/devices/shortcut/addshortcutdialog.cpp
- plugins/devices/shortcut/addshortcutdialog.h
> Optimize the startup method of custom shortcut keys

- plugins/account/userinfo/createuserdialog.cpp
- plugins/system/defaultapp/defaultapp.cpp
Desc:解决BUG#增加部分视频格式
Fix:Userinfo
Desc:解决BUG#17609新建用户无组冲突提示
> Fix:DefaultApp

- plugins/personalized/theme/theme.cpp
- plugins/system/display/widget.cpp
Description: 关闭特效模式后，透明度未恢复
Bug: http://172.17.66.192/biz/bug-view-24388.html
> fix(theme): Gsettings value has not been reset when close effect mode.

- plugins/devices/audio/ukmedia_input_widget.cpp
- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_main_widget.h
- plugins/devices/audio/ukmedia_output_widget.cpp
- plugins/devices/audio/ukmedia_sound_effects_widget.cpp
- plugins/devices/audio/ukmedia_sound_effects_widget.h
- plugins/devices/audio/ukui_custom_style.cpp
- plugins/devices/audio/ukui_custom_style.h
Link:http://172.17.66.192/biz/bug-view-22817.html
> Fix:添加修改提示音大小的功能

- group-manager-server/group_manager_server.cpp
- group-manager-server/group_manager_server.h
- group-manager-server/org.ukui.groupmanager.xml
- plugins/account/userinfo/changegroupdialog.cpp
- plugins/account/userinfo/changegroupdialog.h
- plugins/account/userinfo/creategroupdialog.cpp
- plugins/account/userinfo/definegroupitem.cpp
- plugins/account/userinfo/editgroupdialog.cpp
- plugins/account/userinfo/editgroupdialog.h
> Fix: default group deletion logic && Optimize user display

- debian/control
- plugins/devices/audio/audio.pro
- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_main_widget.h
- shell/res/i18n/bo.ts
- shell/res/i18n/en_US.ts
- shell/res/i18n/tr.ts
- shell/res/i18n/zh_CN.ts
> Fix：解决部分机器调节报警音失败的问题

- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_sound_effects_widget.cpp
- plugins/devices/audio/ukmedia_sound_effects_widget.h
Link:http://172.17.66.192/biz/bug-view-20072.html
> Fix:解决声音效果由custom切换到default，提示声并未变化为雨滴的问题

- plugins/devices/mouse/mouse.pro
- plugins/devices/touchpad/touchpad.pro
- plugins/personalized/theme/theme.pro
Fix build on openSUSE, Make sure library links check will be success.
> Fix library links.

- plugins/devices/audio/ukmedia_main_widget.cpp
1.解决修改配置选项导致控制面板异常退出的问题 
2.Remove the same input and output devices
> Fix some problems caused by modifying the configuration file

- plugins/personalized/theme/theme.cpp
> theme name changed so update code of ukcc

- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/changepwddialog.h
- plugins/account/userinfo/createuserdialog.cpp
Description: 密码校验未生效（包含用户名、相似性）
> Fix(userinfo): pws check with username invalid

- plugins/system/defaultapp/defaultapp.cpp
- plugins/system/defaultapp/defaultapp.h
> Fix: modify default invalid

- commonComponent/ComboxFrame/comboxframe.cpp
- commonComponent/ComboxFrame/comboxframe.h
- plugins/messages-task/notice/notice.cpp
- plugins/messages-task/notice/realizenotice.cpp
- plugins/messages-task/notice/realizenotice.h
- plugins/system/display/declarative/qmloutputcomponent.cpp
- plugins/system/display/outputconfig.cpp
- plugins/system/display/qml/main.qml
- plugins/system/display/resolutionslider.cpp
- plugins/system/display/resolutionslider.h
- plugins/system/display/widget.cpp
- plugins/system/display/widget.h
- plugins/system/power/power.cpp
- plugins/system/power/power.h
- plugins/system/power/power.ui
- plugins/system/power/powermacrodata.h
- shell/res/i18n/zh_CN.ts
* 开始菜单-控制面板-通知和操作，多次点击后电源统计图标出现蓝色框
* 添加电源按键功能
* 控制面板打开外显后为镜像模式
* 切换到1152*864分辨率后应用，系统黑屏并显示NO SUPPORT，无法进去系统桌面，重启后也无法进入
* 首次登录打开侧面通知拦，点击顶部设置按钮，打开控制面板，关闭通知按钮，控制面板闪退
* 系统亮度剩余20%，控制面板亮度显示为0%
* 添加低电量执行操作行为
* 更新翻译
> Fix stable version bugs

- plugins/system/defaultapp/defaultapp.cpp
> Fix: invalid 3gp && asf && rm

- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/changepwddialog.ui
Desc: fix user can not change pwd
> Fix: userinfo

- commonComponent/Uslider/uslider.cpp
- plugins/account/networkaccount/networkaccount.cpp
- plugins/personalized/fonts/fonts.cpp
- plugins/personalized/theme/theme.cpp
- plugins/plugins.pro
- shell/customstyle.cpp
- shell/mainwindow.cpp
- shell/mainwindow.h
- shell/mainwindow.ui
- shell/prescene.cpp
- shell/prescene.h
- shell/res/i18n/zh_CN.ts
* 修复图标主题为空的问题
* 切换字体为华文新魏，字体大小界面出现重叠
* 更改主题名称
* 云账户搜索无法跳转
* 添加应用窗口图标
* 更新翻译
> Fix stable version bug

- plugins/account/userinfo/changevaliddialog.cpp
- registeredQDbus/sysdbusregister.cpp
- registeredQDbus/sysdbusregister.h
> Fix: bug 25546 change passwd aging invalid

- registeredQDbus/sysdbusregister.h
> Fix:(userinfo.valid)

- plugins/account/userinfo/userinfo.cpp
- shell/mainwindow.cpp
- shell/utils/utils.cpp
> Fix:userinfo

- plugins/account/userinfo/changegroupdialog.cpp
- plugins/account/userinfo/changegroupdialog.ui
- plugins/account/userinfo/creategroupdialog.cpp
- plugins/account/userinfo/creategroupdialog.ui
- plugins/account/userinfo/editgroupdialog.cpp
- plugins/account/userinfo/editgroupdialog.ui
- plugins/devices/shortcut/showallshortcut.ui
> Update: heading horizontally aligned

- plugins/devices/audio/ukmedia_main_widget.cpp
Link:http://172.17.66.192/biz/bug-view-28797.html
> Fix:首次打开控制面板-设备-声音，将提示音开关打开，调节提示音后控制面板闪退的问题

- plugins/account/userinfo/creategroupdialog.cpp
- plugins/account/userinfo/creategroupdialog.h
- plugins/account/userinfo/editgroupdialog.cpp
- plugins/account/userinfo/editgroupdialog.h
> Fix: bug 30145 Group members are not displayed

- shell/res/resfile.qrc
- shell/res/search.xml
- shell/shell.pro
- ukui-control-center.pro
Description: 添加供搜索调用的可搜索配置项xml文件
> feat(search): Add search.xml which is provided to ukui-search

- shell/mainwindow.cpp
- shell/utils/utils.cpp
> Fix:(MainWindow)

- plugins/system/defaultapp/defaultapp.cpp
> Fix: default image app

- plugins/system/defaultapp/defaultapp.cpp
- plugins/system/defaultapp/defaultapp.h
> Optimize code logic of DefaultApp

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/bluetoothmain.h
- plugins/devices/bluetooth/bluetoothnamelabel.cpp
- plugins/devices/bluetooth/bluetoothnamelabel.h
- plugins/devices/bluetooth/deviceinfoitem.cpp
- plugins/devices/bluetooth/deviceinfoitem.h
- shell/res/i18n/bo.ts
- shell/res/i18n/en_US.ts
- shell/res/i18n/tr.ts
- shell/res/i18n/zh_CN.ts
Adjust equipment item dynamics;
globalization;
> Fix renaming exception;

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/bluetoothnamelabel.cpp
- plugins/devices/bluetooth/bluetoothnamelabel.h
- plugins/devices/bluetooth/deviceinfoitem.cpp
- plugins/devices/bluetooth/deviceinfoitem.h
- shell/res/i18n/bo.ts
- shell/res/i18n/en_US.ts
- shell/res/i18n/tr.ts
- shell/res/i18n/zh_CN.ts
Fix renaming exception;
Adjust equipment item dynamics;
globalization;
> Repair Features

- plugins/system/defaultapp/defaultapp.cpp
> Fix: bug 31313 The theme icon is not displayed

- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_main_widget.h
> Fix:解决连接器不随输出设备改变的问题

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/bluetoothmain.h
- plugins/devices/bluetooth/bluetoothnamelabel.cpp
- plugins/devices/bluetooth/bluetoothnamelabel.h
- plugins/devices/bluetooth/deviceinfoitem.cpp
- plugins/devices/bluetooth/deviceinfoitem.h
Fix duplicate Bluetooth devices;
> Repair the theme switch Bluetooth interface is not highlighted;

- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/changevaliddialog.cpp
- plugins/account/userinfo/createuserdialog.cpp
- plugins/account/userinfo/userinfo.cpp
- plugins/account/userinfo/userinfo.pro
- plugins/system/autoboot/autoboot.cpp
- shell/utils/utils.cpp
Desc:解决BUG#22351 【控制面板|键盘】右键任务栏键盘布局，点击首选项，概率唤不起控制面板
Desc:解决BUG#31783 【开机启动】火狐浏览器图标不正确
Desc:解决BUG  #24642 【控制面板|账户】更改密码时，输完当前密码后点击新密码输入框时，下方会闪过一行字
Desc:解决BUG #31633 【控制面板】更改密码后控制面板卡死
> Fix(UserInfo,AutoBoot)

- plugins/devices/shortcut/addshortcutdialog.cpp
- plugins/devices/shortcut/addshortcutdialog.ui
- plugins/devices/shortcut/shortcut.cpp
- plugins/devices/shortcut/shortcut.ui
- shell/res/i18n/en_US.ts
- shell/res/i18n/zh_CN.ts
> Add: max width 960 shortcut Ui

- plugins/account/userinfo/changefacedialog.cpp
- plugins/account/userinfo/changefacedialog.h
- plugins/account/userinfo/changefacedialog.ui
- plugins/account/userinfo/changegroupdialog.cpp
- plugins/account/userinfo/changegroupdialog.ui
- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/changepwddialog.ui
- plugins/account/userinfo/changetypedialog.cpp
- plugins/account/userinfo/changetypedialog.ui
- plugins/account/userinfo/changevaliddialog.cpp
- plugins/account/userinfo/changevaliddialog.ui
- plugins/account/userinfo/creategroupdialog.cpp
- plugins/account/userinfo/creategroupdialog.ui
- plugins/account/userinfo/createuserdialog.cpp
- plugins/account/userinfo/createuserdialog.ui
- plugins/account/userinfo/delgroupdialog.cpp
- plugins/account/userinfo/delgroupdialog.ui
- plugins/account/userinfo/deluserdialog.cpp
- plugins/account/userinfo/deluserdialog.h
- plugins/account/userinfo/deluserdialog.ui
- plugins/account/userinfo/userinfo.cpp
- plugins/account/userinfo/userinfo.ui
- plugins/devices/keyboard/keyboardcontrol.cpp
- plugins/devices/keyboard/keyboardcontrol.h
- plugins/devices/keyboard/keyboardcontrol.ui
- plugins/system/autoboot/addautoboot.cpp
- plugins/system/autoboot/addautoboot.ui
> Fix:Userinfo,Keyboard,Autoboot

- plugins/network/proxy/proxy.cpp
- shell/mainwindow.cpp
- shell/utils/utils.cpp
Desc: Hide http proxy cetification
DeSC: Hide backup When strict
> Fix: Proxy, Shell

- shell/res/resfile.qrc
> add pictures

- plugins/security-updates/upgrade/src/appupdate.cpp
- plugins/security-updates/upgrade/src/appupdate.h
- plugins/security-updates/upgrade/src/m_updatelog.cpp
- plugins/security-updates/upgrade/src/m_updatelog.h
- plugins/security-updates/upgrade/src/tabwidget.cpp
- plugins/security-updates/upgrade/src/updatedbus.cpp
- plugins/security-updates/upgrade/src/updatedbus.h
- plugins/security-updates/upgrade/src/updatesource.cpp
> bugs for update

- plugins/system/display/declarative/qmloutput.cpp
- plugins/system/display/declarative/qmlscreen.cpp
- plugins/system/display/declarative/qmlscreen.h
- plugins/system/display/qml/Output.qml
- plugins/system/display/qml/main.qml
> fix(display): limit display position

- plugins/system/display/widget.cpp
- plugins/system/display/widget.h
> Feature(display): Add a new configuration file for resolution Settings.

- plugins/account/userinfo/changegroupdialog.cpp
- plugins/account/userinfo/changegroupdialog.ui
- plugins/account/userinfo/creategroupdialog.cpp
- plugins/account/userinfo/creategroupdialog.ui
- plugins/account/userinfo/delgroupdialog.cpp
- plugins/account/userinfo/delgroupdialog.ui
- plugins/account/userinfo/editgroupdialog.cpp
- plugins/account/userinfo/editgroupdialog.ui
> Modify group dialog specification

- plugins/system/defaultapp/defaultapp.cpp
> Fix: defaultapp restore invalid

- plugins/system/defaultapp/defaultapp.cpp
> Fix: bug defaultapp restore invalid

- plugins/account/userinfo/userinfo.cpp
> Fix: Under the separation of powers, group invalid

- plugins/security-updates/upgrade/src/appupdate.cpp
- plugins/security-updates/upgrade/src/appupdate.h
- plugins/security-updates/upgrade/src/backup.cpp
- plugins/security-updates/upgrade/src/backup.h
- plugins/security-updates/upgrade/src/historyupdatelistwig.cpp
- plugins/security-updates/upgrade/src/m_updatelog.cpp
- plugins/security-updates/upgrade/src/m_updatelog.h
- plugins/security-updates/upgrade/src/mylabel.cpp
- plugins/security-updates/upgrade/src/mylabel.h
- plugins/security-updates/upgrade/src/tabwidget.cpp
- plugins/security-updates/upgrade/src/tabwidget.h
- plugins/security-updates/upgrade/src/ukscconn.cpp
- plugins/security-updates/upgrade/src/updatedbus.cpp
- plugins/security-updates/upgrade/src/updatedbus.h
- plugins/security-updates/upgrade/src/updatelog.cpp
- plugins/security-updates/upgrade/src/updatesource.cpp
- plugins/security-updates/upgrade/src/updatesource.h
- plugins/security-updates/upgrade/src/upgrademain.cpp
- plugins/security-updates/upgrade/src/upgrademain.h
- plugins/security-updates/upgrade/upgrade.pro
- shell/res/i18n/zh_CN.ts
> upgrade translation and others

- plugins/personalized/desktop/desktop.cpp
> Fix: Desktop

- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_main_widget.h
Link: http://172.17.66.192/biz/bug-view-33827.html
> Fix:解决插入耳机时调节不了输出音量的问题

- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
> Fix:some bugs

- plugins/security-updates/upgrade/src/updatedbus.cpp
- shell/main.cpp
- shell/res/i18n/en_US.ts
- shell/res/i18n/zh_CN.ts
Description: fix no icon by notify dbus
Log: 修复通知区域无图标
> fix(notify): fix no icon by notify dbus

- plugins/security-updates/upgrade/src/appupdate.cpp
- plugins/security-updates/upgrade/src/appupdate.h
- plugins/security-updates/upgrade/src/tabwidget.cpp
- plugins/security-updates/upgrade/src/updatedbus.cpp
- plugins/security-updates/upgrade/src/utils.h
> upgrade changes

- plugins/account/networkaccount/dbusutils.cpp
- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
翻译文件：MainWidget.cpp Waitting for sync! 等候同步！
> FIx:bug#36600

- shell/res/i18n/en_US.ts
- shell/res/i18n/zh_CN.ts
Description: update translation
Log: 更新翻译
> chore(translation): update translation

- plugins/account/networkaccount/maindialog.h
麻烦看下Mainwidget.cpp是否有没翻译的文本 如果有 应该是 ：Network can  not reach! ---- 网络不可达！ 谢谢~
> Fix:remove empty slots

- commonComponent/Uslider/uslider.cpp
- shell/mainwindow.cpp
- shell/qtsingleapplication/qtsingleapplication.cpp
> Fix: interface flickers when awake from taskbar

- plugins/security-updates/upgrade/src/appupdate.cpp
- plugins/security-updates/upgrade/src/historyupdatelistwig.cpp
- plugins/security-updates/upgrade/src/historyupdatelistwig.h
- plugins/security-updates/upgrade/src/m_updatelog.cpp
- plugins/security-updates/upgrade/src/m_updatelog.h
- plugins/security-updates/upgrade/src/mylabel.cpp
- plugins/security-updates/upgrade/src/tabwidget.cpp
- plugins/security-updates/upgrade/src/updatelog.cpp
> some changes of update

- plugins/security-updates/upgrade/src/appupdate.cpp
- plugins/security-updates/upgrade/src/updatedbus.cpp
- plugins/security-updates/upgrade/src/updatedbus.h
> 系统更新：修改文件锁位置

- debian/changelog
- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
- shell/res/i18n/zh_CN.ts
1、整理了下mainwidget.cpp文件，使得整体效率变快
2、更新了翻译
> Fix:optimazed the code && update translation -dev stable

- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
- shell/res/i18n/zh_CN.ts
1、整理了下mainwidget.cpp文件，使得整体效率变快
2、更新了翻译
> Fix:optimazed code && update translation 

- plugins/system/autoboot/autoboot.cpp
> Add background auto start screenshot

- plugins/account/networkaccount/mainwidget.cpp
> Fix:Set auto-sync switch disable when first login

- plugins/messages-task/about/about.cpp
- plugins/messages-task/about/about.h
> Fix: update memory display

- .github/workflows/build.yml
- checkUserPwdWithPAM/checkUserPwd/auth-pam.cpp
- checkUserPwdWithPAM/checkUserPwd/auth-pam.h
- checkUserPwdWithPAM/checkUserPwd/auth.h
- checkUserPwdWithPAM/checkUserPwd/checkUserPwd.pro
- checkUserPwdWithPAM/checkUserPwd/main.cpp
- checkUserPwdWithPAM/checkUserPwd/widget.cpp
- checkUserPwdWithPAM/checkUserPwd/widget.h
- checkUserPwdWithPAM/checkUserPwdWithPAM.pro
- checkUserPwdWithPAM/childCheckPwdWithPAM/childCheckPwdWithPAM.pro
- checkUserPwdWithPAM/childCheckPwdWithPAM/main.cpp
- checkUserPwdWithPAM/conf/control-center
- debian/control
- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/changepwddialog.h
- plugins/account/userinfo/changepwddialog.ui
- plugins/account/userinfo/pwdcheckthread.cpp
- plugins/account/userinfo/pwdcheckthread.h
- plugins/account/userinfo/userinfo.cpp
- plugins/account/userinfo/userinfo.pro
- plugins/system/power/power.cpp
- registeredQDbus/conf/com.control.center.qt.systemdbus.policy
- registeredQDbus/registeredQDbus.pro
- registeredQDbus/run-passwd2.cpp
- registeredQDbus/run-passwd2.h
- registeredQDbus/sysdbusregister.cpp
- registeredQDbus/sysdbusregister.h
- ukui-control-center.pro
Desc1:
构建sysdbus方法，使用passwd修改密码同时统一修改当前用户及其他用户密码流程，支持国密算法
去掉旧的当前密码校验改为封装的pam密码检验流程，解决修改完密码后的主进程阻塞问题
Desc2:
电源通用设置无功能时隐藏“通用设置”
> Fix:UserInfo;Power

- plugins/devices/shortcut/defineshortcutitem.cpp
- plugins/devices/touchpad/touchpad.cpp
> Fix: disable touchpad finger scroll invalid

- plugins/devices/audio/ukmedia_main_widget.cpp
Link: http://172.17.66.192/biz/bug-view-36756.html
> Fix:解决更改系统主题为深色主题时控制面板声音图标显示不清楚的问题

- plugins/messages-task/about/about.cpp
- plugins/messages-task/about/about.ui
- shell/res/i18n/bo.ts
- shell/res/i18n/en_US.ts
- shell/res/i18n/tr.ts
- shell/res/i18n/zh_CN.ts
> 修改硬盘部分显示的格式

- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
> Add:adjust Kylin-id dev stable

- shell/main.cpp
- shell/shell.pro
- shell/utils/utils.cpp
- shell/utils/utils.h
Description: use QSGRendererInterface::Software
指定Qt Quick场景图形后端
> fix(display): use QSGRendererInterface::Software

- plugins/account/networkaccount/logindialog.cpp
- plugins/account/networkaccount/mainwidget.cpp
> Fix:Switchbutton can not move

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
> Fix: network status error when modify connection name

- plugins/account/networkaccount/logindialog.cpp
> Fix: update phone regexp

- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
> Add:adjust Kylin-id client

- plugins/account/userinfo/createuserdialog.ui
> Modify the error prompt font color of adding users to red.

- shell/ukccabout.cpp
- shell/ukccabout.h
> Solve the problem that the developer mailbox is not clickable.

- plugins/account/networkaccount/areacodelineedit.cpp
- plugins/account/networkaccount/configfile.cpp
- plugins/account/networkaccount/logindialog.cpp
- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mcodewidget.cpp
- plugins/account/networkaccount/switchbutton.cpp
- plugins/account/networkaccount/tips.cpp
Fix bug that user will see the sign off page when login on first time open ukcc
> Fix:optimazed the code

- plugins/account/networkaccount/logindialog.cpp
- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/mainwidget.cpp
修复了用户打开控制面板时，打开云账户会闪一下登出界面的BUG
> Dev stable:Fix bug that user will see the sign off page when login on first time open ukcc

- plugins/system/autoboot/autoboot.cpp
- shell/mainwindow.cpp
> Fix: add app autoboot fail

- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
- plugins/account/networkaccount/switchbutton.cpp
- plugins/account/networkaccount/switchbutton.h
> Fix:disbale switch when network unconnected

- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
- plugins/account/networkaccount/switchbutton.cpp
- plugins/account/networkaccount/switchbutton.h
> Fix:disable switch when network unconnected

- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/mainwidget.cpp
> Fix:bug #40387

- plugins/system/display/declarative/qmlscreen.cpp
- plugins/system/display/declarative/qmlscreen.h
- plugins/system/display/widget.cpp
- shell/ukccabout.cpp
1.解决双屏显示热插拔时位置问题；2.给邮件地址添加下划线以及其上鼠标样式；
> 1.解决双屏显示热插拔时位置问题；2.给邮件地址添加下划线以及其上鼠标样式；

- plugins/system/display/declarative/qmlscreen.cpp
- plugins/system/display/declarative/qmlscreen.h
- plugins/system/display/widget.cpp
> 恢复热插拔问题代码.

- plugins/security-updates/upgrade/src/tabwidget.cpp
- plugins/security-updates/upgrade/src/tabwidget.h
解决没有更新信息时的翻译问题；解决部分情况下点击全部更新无反应的问题。
> 系统更新：禅道bug解决

- checkUserPwd/main.cpp
- plugins/account/userinfo/changefacedialog.h
- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/qtdbus/userdispatcher.h
- plugins/account/userinfo/run-passwd.cpp
- plugins/account/userinfo/userinfo.cpp
- plugins/devices/audio/ukmedia_main_widget.h
- plugins/devices/keyboard/kbdlayoutmanager.cpp
- plugins/devices/mouse/mousecontrol.cpp
- plugins/devices/shortcut/realizeshortcutwheel.h
- plugins/devices/shortcut/shortcut.cpp
- plugins/devices/touchpad/touchpad.cpp
- plugins/messages-task/notice/notice.h
- plugins/messages-task/notice/realizenotice.h
- plugins/network/proxy/proxy.h
- plugins/personalized/desktop/realizedesktop.h
- plugins/personalized/fonts/fonts.h
- plugins/personalized/screensaver/screensaver.h
- plugins/personalized/wallpaper/wallpaper.h
- plugins/security-updates/backup/backup.cpp
- plugins/system/autoboot/addautoboot.h
- plugins/system/autoboot/autoboot.cpp
- plugins/system/defaultapp/addappdialog.h
- plugins/system/defaultapp/defaultapp.h
- plugins/time-language/area/area.h
- plugins/time-language/datetime/changtime.h
- plugins/time-language/datetime/datetime.h
- shell/mainwindow.cpp
Description: Not include glib's headers in an 'extern "C"' context
Log: 去除extern "C"
> fix: Not include glib's headers in an 'extern "C"' context

- plugins/system/display/declarative/qmlscreen.cpp
- plugins/system/display/declarative/qmlscreen.h
- plugins/system/display/widget.cpp
1.  解决热插拔图标位置变化问题;
2. 解决统一输出热插拔没有图标问题;
> 1.  解决热插拔图标位置变化问题; 2. 解决统一输出热插拔没有图标问题;

- group-manager-server/conf/org.ukui.groupmanager.policy
- plugins/account/userinfo/changegroupdialog.cpp
- plugins/account/userinfo/changegroupdialog.h
> Fix: policy prompt error

- plugins/messages-task/about/about.cpp
- plugins/messages-task/about/about.ui
- plugins/personalized/theme/theme.cpp
- plugins/personalized/theme/theme.h
- shell/res/i18n/en_US.ts
- shell/res/i18n/zh_CN.ts
> style: adjust ui

- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
> Fix:Optimazed network status judgement

- plugins/system/defaultapp/defaultapp.cpp
> Fix: Change the default browser to qaxbrowser

- plugins/account/networkaccount/areacodelineedit.cpp
- plugins/account/networkaccount/blueeffect.cpp
- plugins/account/networkaccount/combobox.cpp
- plugins/account/networkaccount/dbusutils.cpp
- plugins/account/networkaccount/frameitem.cpp
- plugins/account/networkaccount/itemlist.cpp
- plugins/account/networkaccount/logindialog.cpp
- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mcodewidget.cpp
- plugins/account/networkaccount/passdialog.cpp
- plugins/account/networkaccount/passwordlineedit.cpp
- plugins/account/networkaccount/regdialog.cpp
- plugins/account/networkaccount/successdiaolog.cpp
- plugins/account/networkaccount/svghandler.cpp
- plugins/account/networkaccount/switchbutton.cpp
- plugins/account/networkaccount/syncdialog.cpp
> Fix: Beautify the code && Optimazed network status

- plugins/account/networkaccount/areacodelineedit.cpp
- plugins/account/networkaccount/blueeffect.cpp
- plugins/account/networkaccount/combobox.cpp
- plugins/account/networkaccount/dbusutils.cpp
- plugins/account/networkaccount/frameitem.cpp
- plugins/account/networkaccount/itemlist.cpp
- plugins/account/networkaccount/logindialog.cpp
- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mcodewidget.cpp
- plugins/account/networkaccount/passdialog.cpp
- plugins/account/networkaccount/passwordlineedit.cpp
- plugins/account/networkaccount/regdialog.cpp
- plugins/account/networkaccount/successdiaolog.cpp
- plugins/account/networkaccount/svghandler.cpp
- plugins/account/networkaccount/switchbutton.cpp
- plugins/account/networkaccount/syncdialog.cpp
> Fix:Beautify the code && Optimazed network status

- plugins/network/vino/sharemain.cpp
- plugins/network/vino/sharemain.h
- plugins/network/vino/vino.pro
Description: Change swicthButton and password reminders
Log: 更改样式
> fix(network): Display bug for network

- plugins/devices/shortcut/shortcut.cpp
> Fix: shield Ctrl+Alt+A

- plugins/account/networkaccount/mainwidget.cpp
> Fix:bug#42991 wrong page when first login

- plugins/account/networkaccount/logindialog.cpp
> Fix:bug #43388 QLineEdit can not change correctly

- plugins/account/networkaccount/logindialog.cpp
> Fix:bug#43388 QLineEdit can not change correctly

- plugins/devices/audio/ukmedia_main_widget.cpp
Link: http://172.17.66.192/biz/bug-view-43062.html
> Fix:解决调节任务栏托盘音量，控制面板图标未跟随变化的问题

- plugins/account/networkaccount/mainwidget.cpp
修复在没网的情况打开控制面板不能正常切换没网的界面状态的问题。
> Fix:Can not recognize the network status

- plugins/account/userinfo/changegroupdialog.ui
- plugins/account/userinfo/changepwddialog.ui
- plugins/account/userinfo/changetypedialog.ui
- plugins/account/userinfo/changevaliddialog.ui
- plugins/account/userinfo/creategroupdialog.ui
- plugins/account/userinfo/createuserdialog.ui
- plugins/devices/shortcut/addshortcutdialog.ui
- plugins/system/autoboot/addautoboot.ui
- plugins/time-language/area/dataformat.ui
- plugins/time-language/datetime/changtime.ui
Description: 调整自定义快捷键边距
Log: 调整自定义快捷键边距
> fix(control-center): adjust margins

- plugins/account/networkaccount/mainwidget.cpp
> Fix:need 2 clicks to make switch on/off 

- plugins/devices/shortcut/addshortcutdialog.cpp
- plugins/devices/shortcut/addshortcutdialog.h
> Add: shortcut input limit

- shell/res/search.xml
> Fix: There is no English translation for search file.

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/deviceinfoitem.cpp
Crash after uninstalling ukui-bluetooth;
> Solve the crash of the paired device;

- plugins/security-updates/upgrade/src/appupdate.cpp
- plugins/security-updates/upgrade/src/m_updatelog.cpp
> 设置系统更新界面，更新信息滑动条样式

- plugins/system/autoboot/autoboot.cpp
> Fix: autoboot shield 360

- plugins/account/networkaccount/dbusutils.cpp
- plugins/account/networkaccount/dbusutils.h
- plugins/account/networkaccount/logindialog.cpp
- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/maindialog.h
- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
> Fix:Optimazed the cloud account's code`

- plugins/account/networkaccount/dbusutils.cpp
- plugins/account/networkaccount/dbusutils.h
- plugins/account/networkaccount/logindialog.cpp
- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/maindialog.h
- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
> Fix:Optimazed the cloud sync's code`

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/shortcut/shortcut.cpp
- shell/mainwindow.h
- shell/searchwidget.cpp
Description: Optimize search function
Log: 优化搜素功能，添加搜索快捷键和蓝牙，去掉不存在的功能搜索
> Optimize search function

- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
> Fix:#bug 47175

- plugins/time-language/datetime/datetime.cpp
- plugins/time-language/datetime/datetime.h
- registeredQDbus/sysdbusregister.cpp
- registeredQDbus/sysdbusregister.h
Description: 联网同步时间同步硬件时间
Log: 通过控制面板的qbus来修改硬件时间同步
> fix(datetime): syncRTC time

- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/mainwidget.cpp
> Fix:bug #48173

- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/mainwidget.cpp
> Fix: bug #48173

- plugins/account/userinfo/changepwddialog.cpp
- plugins/account/userinfo/changepwddialog.h
- plugins/account/userinfo/changetypedialog.cpp
- plugins/account/userinfo/changetypedialog.h
- plugins/account/userinfo/changeusername.cpp
- plugins/account/userinfo/changeusername.h
- plugins/account/userinfo/changeusername.ui
- plugins/account/userinfo/qtdbus/userdispatcher.cpp
- plugins/account/userinfo/qtdbus/userdispatcher.h
- plugins/account/userinfo/userinfo.cpp
- plugins/account/userinfo/userinfo.h
- plugins/account/userinfo/userinfo.pro
- plugins/account/userinfo/userinfo.ui
> Add: Userinfo

- plugins/personalized/desktop/desktop.cpp
Description: 解决调整“显示在托盘上的图标”，逻辑相反的问题
Log: 解决调整“显示在托盘上的图标”，逻辑相反的问题
> fix(desktop): tray app switch

- plugins/account/networkaccount/mainwidget.cpp
> Fix:User can not jump into correct page randomly

- plugins/system/display/resolutionslider.cpp
> Fix: Shielding resolution below 1600 for sw64

- plugins/account/userinfo/creategroupdialog.cpp
> Fix: change group name input limit

- plugins/system/display/controlpanel.h
- plugins/system/display/display.h
- plugins/system/display/outputconfig.cpp
- plugins/system/display/outputconfig.h
- plugins/system/display/widget.cpp
- plugins/system/display/widget.h
> Fraction scale

- plugins/system/display/widget.cpp
Description: bug#43141
Log: 修改分辨率后加延时，得到准确的控制面板位置
>  fix(bug#43141)

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/deviceinfoitem.cpp
- plugins/devices/bluetooth/deviceinfoitem.h
Description: 蓝牙操作调整
Log: 未配对的设备和已配对的键盘鼠标只显示移除操作
> feat(Bluetooth): Bluetooth operation adjustment

- plugins/devices/shortcut/getshortcutworker.cpp
> Fix: shield KP_Delete

- plugins/devices/shortcut/shortcut.cpp
- plugins/time-language/datetime/datetime.cpp
- plugins/time-language/datetime/datetime.ui
- shell/mainwindow.cpp
Description: bug#46711 and bug#45970
Log: 1、恢复快捷键的搜索；2、日期显示跟随字体设置
> bug#46711 and bug#45970

- plugins/account/userinfo/biometricenroll.cpp
- plugins/account/userinfo/biometricmoreinfo.cpp
- plugins/account/userinfo/userinfo.cpp
> Log:指纹驱动gdxfp屏蔽验证按钮,修复验证失败仍显示验证成功的问题

- plugins/devices/shortcut/addshortcutdialog.cpp
- plugins/devices/shortcut/addshortcutdialog.h
- plugins/devices/shortcut/getshortcutworker.cpp
- plugins/devices/shortcut/shortcut.cpp
> Fix: Optimization logic of custom shortcut

- shell/mainwindow.cpp
Description: can't show slider
Log: 无法显示滑动条
Bug: http://pm.kylin.com/biz/bug-view-51227.html
> fix ui width

- plugins/messages-task/search/search.cpp
- plugins/messages-task/search/search.h
- plugins/messages-task/search/search.pro
- shell/res/i18n/zh_CN.ts
- shell/res/search.xml
- shell/res/secondaryleftmenu/Search.svg
> feat(search): Add black-list settings. 

- plugins/personalized/theme/theme.cpp
- plugins/personalized/theme/themewidget.cpp
Description: Display icon adjustment
Log: Display icon adjustment
Bug: 51229
> fix(theme): IconTheme

- plugins/account/userinfo/userinfo.cpp
- plugins/account/userinfo/userinfo.ui
> Fix: Password time effective adaptation for sw

- plugins/account/userinfo/biometricmoreinfo.cpp
- plugins/account/userinfo/biometricmoreinfo.h
- plugins/account/userinfo/userinfo.cpp
- plugins/account/userinfo/userinfo.h
Log:解决账户设置里指纹开关和生物特征管理工具指纹开关不同步
Bug:52292
> fix:biometric switch button event

- plugins/network/vino/sharemain.cpp
Description: Password connection error
Log: Password connection error
Bug: #51523
> fix(Vino): Vino

- plugins/system/display/display.pro
- plugins/system/display/widget.cpp
Description: the monitor preview was blocked
Log:bug#50758:显示延迟，bug#51005:亮度与显示实际不一致
Bug: http://pm.kylin.com/biz/bug-view-50758.html,http://pm.kylin.com/biz/bug-view-51005.html
> fix: the monitor preview was blocked

- plugins/system/autoboot/autoboot.cpp
> Fix: Custom boot app no icon

- plugins/messages-task/search/search.cpp
- plugins/messages-task/search/search.h
- shell/res/i18n/zh_CN.ts
- shell/res/search.xml
Description: 修复删除某个文件夹后黑名单列表未更新的bug
> fix(search): Block list is not refreshed after delete one folder.

- plugins/devices/printer/printer.cpp
Description: PrinterList abnormal
Log: 打印机列表异常
Bug: #50174
> fix(PrinterList): PrinterList

- plugins/system/defaultapp/defaultapp.cpp
> Fix: bug51969 hide reset btn

- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/mainwidget.cpp
Description:Forbidden user paste word into password lineedit
Log:锁屏/WiFi连接/麒麟软件商店口令框支持拷贝、剪切功能，应禁止
Bug:http://pm.kylin.com/biz/bug-view-53007.html
Signed-off-by: David <448283676@qq.com>
> Fix:Forbidden user paste word into pass edit

- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/mainwidget.cpp
Description:Forbidden user paste word into password lineedit
Log:锁屏/WiFi连接/麒麟软件商店口令框支持拷贝、剪切功能，应禁止
Bug:http://pm.kylin.com/biz/bug-view-53007.html
Signed-off-by: David <448283676@qq.com>
> Fix:#bug 53007

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
Description:Replace wireless network access to network information
log:更换无线网络获取网络信息方式
bug:53362
> fix(Netconnect):wireless network 

- plugins/system/autoboot/autoboot.cpp
- plugins/system/autoboot/autoboot.h
Description: Icon not change
Log: 开机启动中程序图标没有跟随图标主题实时变化
Bug: http://172.17.66.192/biz/bug-view-52665.html
> fix(Autostart Icon): Autostart Icon

- plugins/system/power/power.cpp
Description: Close the lid to sleep
Log:  【cpm+已知】【HUAWEI】合盖休眠，开盖按电源键唤醒后触控板失效，外接鼠标可用
Bug: http://172.17.66.192/biz/bug-view-50738.html
> fix(SystemPower): SystemPower

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
description: Dynamically update IP addresses
log: 动态更新IP地址
bug: #54353 【cpm】【HUAWEI】【配件】【V3】【L1】手动设置静态IPV4地址，设置-网络里的网络详情IPV6地址发生改变(提示+必现+不常用功能) - 桌面华为系列
> fix(netconnect):update IP addresses

- plugins/system/power/power.cpp
- plugins/system/power/power.h
Description:  if the lid is present
Log:【cpm+已知】【HUAWEI】【OS】【V3试制】【非用例】测试机拔掉电池后，系统电源缺少设置项。(一般+必现+不常用功能)
Bug: http://pm.kylin.com/biz/bug-view-54814.html
> fix(Closelid option): Closelid option

- plugins/system/autoboot/addautoboot.cpp
Description: Set no_display applicatino
Log: no_display为true的应用不可添加
> fix(Autostart ): Autostart

- plugins/account/userinfo/changefacedialog.cpp
- plugins/personalized/wallpaper/wallpaper.cpp
Description: External devices are not displayed in the sidebar
Log: 【控制面板】更改用户头像时，侧边栏不显示外部设备
Bug: http://pm.kylin.com/biz/bug-view-21194.html
> fix(Custom Avatars and wallpapers): Custom Avatars and wallpapers

- plugins/account/userinfo/changetypedialog.ui
- plugins/account/userinfo/createuserdialog.cpp
- plugins/account/userinfo/createuserdialog.ui
- shell/res/i18n/en_US.ts
- shell/res/i18n/tr.ts
- shell/res/i18n/zh_CN.ts
Bug: BUG#52497【990】【cpm】【HUAWEI】【KOS】【L0】【VN2整机】标准用户的新用户，可以安装软件及更改系统配置，且无授权提示
BUG#51076【控制面板|账户】英文环境创建非法用户，提示信息显示不全
> Change Desc:更新创建用户时不符合用户名规范的部分提示文案;更新“标准用户”的文案

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
- plugins/network/netconnect/netdetail.cpp
- plugins/network/netconnect/netdetail.h
description:Network details added to the negotiation rate display
log:网络详情增加协商速率显示
bug:53731
> feature:Link Speed

- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_main_widget.h
Description: Connecting to the JBL charge4 control panel crashes
Log: 连接JBLcharge4,点击控制面板声音后控制面板闪退
Bug: http://pm.kylin.com/biz/bug-view-55076.html
> fix(audio): Connecting to the JBL charge4 control panel crashes

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/deviceinfoitem.cpp
Description: 解决界面卡顿，界面UI异常问题
Log: 蓝牙设置界面-我的设备-连续点击多次连接按键，设备可以正常连接，但我的设备界面显示状态一直为加载
> fix(Fixed bug): bug#53499/bug#50762

- plugins/system/power/power.cpp
Description: Set PowerModel
Log: 【cpm+已知】【KelvinV5603版本测试】【L1】系统平衡和节能模式效果与系统的默认预期不符(一般+必现+不常用功能)
Bug: http://pm.kylin.com/biz/bug-view-52255.html
> fix(PowerModel): PowerModel

- plugins/system/display/widget.cpp
- plugins/system/display/widget.h
Description: desktop brightness adjustment judgment error
Log: 台式机亮度判断错误
Bug: http://pm.kylin.com/biz/bug-view-55396.html
> fix: desktop brightness adjustment judgment error

- plugins/devices/shortcut/getshortcutworker.cpp
- plugins/devices/shortcut/shortcut.cpp
Description: Optimize interface layout
Log: 【系统设置】英文模式下字符过长导致字符显示不完全
Bug:  53491
> fix(shortcut): Optimize interface layout

- plugins/network/netconnect/netconnect.cpp
description: fixed loading crash
log:修复加载网络崩溃的问题
> fix(netconnect):Click netconnect crash

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
description: Better refresh display after changing network configuration
log:更改网络配置后更好的刷新显示
>  fix(netconnect): refresh after change network config

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/deviceinfoitem.cpp
Description: BT刷新键不可用，开关BT恢复
Log:
> fix(Bluetooth): Fixed [cpm]bug#55526

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/bluetoothmain.h
- plugins/devices/bluetooth/deviceinfoitem.cpp
Description: 修改控制面板蓝牙模块，动态剔除不在范围的蓝牙设备[cpm]#54436
Log: [cpm]#54436
> fix(bluetooth): 修改控制面板蓝牙模块，动态剔除不在范围的蓝牙设备

- plugins/devices/audio/ukmedia_main_widget.cpp
- plugins/devices/audio/ukmedia_main_widget.h
fix(audio):解决插入USB摄像头时控制面板没有识别输入设备的问题 ;连接蓝牙后，输入输出设备出现多个重复的耳机设备;同时插入带话筒的摄像头和3.5mm耳机，输入设备显示两个话筒
> Fix bug:#55151 #55908 #56270

- plugins/personalized/screensaver/screensaver.cpp
- plugins/personalized/screensaver/screensaver.h
- plugins/personalized/screensaver/screensaver.pro
- plugins/personalized/screensaver/screensaver.ui
- plugins/system/display/widget.cpp
- plugins/system/display/widget.h
- shell/main.cpp
- shell/mainwindow.cpp
Description: 修复一些bug
Log: 1、把屏保恢复成原来的版本；2、修复程序退出线程运行导致段错误的bug；3、暂时隐藏毛玻璃效果(旧屏保透明有显示问题)
> fix(screensaver and display): fix bug

- plugins/system/display/widget.cpp
- plugins/system/display/widget.h
Description: 修复线程未结束导致段错误的bug
Log: 修复线程未结束导致段错误的bug
> fix(display): fix bug

- commonComponent/CloseButton/closebutton.cpp
- plugins/account/networkaccount/logindialog.cpp
- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
description: Display error in login dialog
log:输入提示信息显示有误，时而显示手机/账号 时而显示 手机/账号/邮箱
bug:无，自测问题
> Fix:Display error in login dialog

- plugins/account/networkaccount/logindialog.cpp
- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
description: Display error in login dialog
log:输入提示信息显示有误，时而显示手机/账号 时而显示 手机/账号/邮箱
bug:无，自测问题
> Fix:Display error on login dialog

- plugins/network/netconnect/netconnect.cpp
description: Quickly switching network mode causes ukui-control-center crash
log:快速切换网络模式导致控制面板崩溃
bug:56365
> V10 fix(netconnect):Quickly switching network mode causes ukui-control-center crash

- plugins/network/netconnect/netconnect.cpp
description: Quickly switching network mode causes ukui-control-center crash
log:快速切换网络模式导致控制面板崩溃
bug:56365
> 990:fix(netconnect):Quickly switching network mode causes ukui-control-center crash

- plugins/system/defaultapp/addappdialog.cpp
- plugins/system/defaultapp/addappdialog.h
- plugins/system/defaultapp/defaultapp.cpp
- plugins/system/defaultapp/defaultapp.h
- plugins/system/defaultapp/defaultapp.ui
> Fix(defaultapp): Optimize starting speed

- plugins/system/display/widget.cpp
> Kirin 21 0522

- plugins/security-updates/upgrade/src/tabwidget.cpp
- plugins/security-updates/upgrade/src/tabwidget.h
descrption:No longer receive backup and restore signal after the backup is completed
log: 备份完成后不再接收备份还原信号
bug: #55220 【控制面板|更新】打开更新界面，然后使用备份还原工具进行备份操作，更新界面会自动计算系统空间
> fix(upgrade):

- plugins/account/userinfo/changegroupdialog.cpp
- plugins/account/userinfo/userinfo.cpp
- plugins/devices/printer/printer.cpp
- plugins/devices/shortcut/shortcut.cpp
- plugins/messages-task/notice/notice.cpp
- plugins/messages-task/search/search.cpp
- plugins/messages-task/search/search.pro
- plugins/network/vpn/vpn.cpp
- plugins/system/autoboot/autoboot.cpp
- plugins/time-language/area/area.cpp
Description: fix some hover questions
Log: 修复hover部件的悬浮问题和显示问题
> fix(UI:hover questions): UI:hover questions

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
description:Network details are folded when switching network
log：切换网络时网络详情收起
bug:57124
> fix(netconnect):Network Details

- shell/res/secondaryleftmenu/Search.svg
- shell/res/secondaryleftmenu/SearchWhite.svg
Description: 应设计师要求替换插件图标
Log: 替换插件图标
> feat(search): Replace plugin icon.

- plugins/network/netconnect/netconnect.cpp
description:Avoid jitter when refreshing
log:避免刷新时抖动
bug:57688
> fix(netconnect)Avoid jitter when refreshing

- plugins/network/vino/inputpwddialog.cpp
- plugins/network/vino/inputpwddialog.h
- plugins/network/vino/sharemain.cpp
- plugins/network/vino/sharemain.h
- plugins/network/vino/vino.pro
Description: Add Password popup
Log: 增加密码弹窗
> fix(Vino Desktop sharing): Desktop sharing

- commonComponent/SwitchButton/switchbutton.cpp
Description: display dialog error
Log: 【系统设置】关闭电源统计也会弹出设置框
Bug: http://pm.kylin.com/biz/bug-view-57101.html
> fix(NoticeOringin): NoticeOringin

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
- plugins/network/netconnect/netdetail.cpp
- plugins/network/netconnect/netdetail.h
log:修复界面发生抖动问题
bug:57929
log:在控制面板点击刷新，列表wifi信息没有更新
bug:57102
log:网络连接有线网络后，在控制面板-网络连接中没有显示已经连接上的网络
bug:56581
log:在控制面板中无法关闭wifi按钮
bug:57510
> fix(netconnect): Fix

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
> Unable to open ukui-control-center

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
- plugins/network/netconnect/netdetail.cpp
- plugins/network/netconnect/netdetail.h
log:修复网络列表更新异常的问题
bug:57102
The cable network is displaying an abnormal problem
log:有线网络显示异常问题
bug:56581
Unable to turn off wireless network switch problem
log:无法关闭无线网络开关问题
bug:57510
> fix(netconnect)Fix network list update anomaly

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
- plugins/network/netconnect/netdetail.cpp
- plugins/network/netconnect/netdetail.h
> fix(netconnect):去掉未使用的槽函数防止插件加载失败

- plugins/account/userinfo/changefacedialog.ui
- plugins/account/userinfo/changegroupdialog.ui
- plugins/account/userinfo/changepwddialog.ui
- plugins/account/userinfo/changetypedialog.cpp
- plugins/account/userinfo/changetypedialog.h
- plugins/account/userinfo/changetypedialog.ui
- plugins/account/userinfo/changevaliddialog.ui
- plugins/account/userinfo/creategroupdialog.cpp
- plugins/account/userinfo/creategroupdialog.ui
- plugins/account/userinfo/createuserdialog.ui
- plugins/account/userinfo/delgroupdialog.cpp
- plugins/account/userinfo/delgroupdialog.h
- plugins/account/userinfo/delgroupdialog.ui
- plugins/account/userinfo/editgroupdialog.cpp
- plugins/account/userinfo/editgroupdialog.ui
- plugins/account/userinfo/userinfo.cpp
- plugins/devices/shortcut/addshortcutdialog.ui
- plugins/messages-task/notice/appdetail.ui
- plugins/system/autoboot/addautoboot.ui
- plugins/time-language/area/dataformat.ui
Description: Adjust some dialog
Log: 调整部分弹窗UI问题
> fix(Dialog questions):  Dialog questions

- plugins/messages-task/about/about.cpp
Description: Activation page
Log: 激活页面提示“未激活”“已过期”等异常状态文字显示颜色不对
Task: http://pm.kylin.com/biz/story-view-6416.html
> fix(About): About

- plugins/network/netconnect/netconnect.cpp
> fix(netconnect):任务栏wifi列表与控制面板wifi列表不一致

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/bluetoothmain.h
- plugins/devices/bluetooth/deviceinfoitem.cpp
Description: Fixed BUG#57885
Log: 笔记本休眠/睡眠后唤醒，蓝牙与睡眠前状态不一致
> fix(Bluetooth): Fixed Bug

- plugins/account/userinfo/changegroupdialog.cpp
- plugins/account/userinfo/userinfo.cpp
- plugins/devices/keyboard/keyboardcontrol.cpp
- plugins/devices/shortcut/shortcut.cpp
- plugins/messages-task/notice/notice.cpp
- plugins/network/proxy/proxy.cpp
- plugins/personalized/wallpaper/wallpaper.cpp
- plugins/system/autoboot/autoboot.cpp
- plugins/system/display/widget.cpp
- plugins/time-language/area/area.cpp
- plugins/time-language/datetime/datetime.cpp
Description: Adjust some Dialogs
Log:  弹出窗口位置不对
Task: http://pm.kylin.com/biz/story-view-6494.html
> fix(some Dialogs): some Dialogs

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/bluetoothmain.h
- plugins/devices/bluetooth/deviceinfoitem.cpp
- plugins/devices/bluetooth/deviceinfoitem.h
Description: bluetooth
Log:蓝牙去掉刷新按键，修改扫描到的蓝牙设备图片为默认图标问题
Bug: http://pm.kylin.com/biz/bug-view-53125.html
>     fix:bluetooth

- plugins/network/netconnect/netconnect.cpp
> fix(netconnect) Add connection speed units

- plugins/system/defaultapp/defaultapp.cpp
- shell/searchwidget.cpp
Description: 在控制面板可以搜索到已取消功能 && 默认应用加载失败
Log: bug58580
> fix(search): Shielding password effectiveness in search

- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/mainwidget.cpp
Description: 修复云账户登录内置对话框不居中于应用的问题
Log: bug#59294
> Fix:bug #59294

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
> fix(netconnect):当获取到的ipv6网关为空时，显示为空

- plugins/messages-task/about/about.cpp
- plugins/messages-task/about/about.h
- plugins/messages-task/about/about.ui
Description: About Ui error
Log: 【系统授权】设置系统字体大小为16，激活到期后界面内容显示不全
Bug: http://pm.kylin.com/biz/bug-view-58936.html
> fix(About UI): About UI

- plugins/devices/bluetooth/bluetoothmain.cpp
Description: bluetooth-cpm bug
Log: 已配对连接的设备删除时间长，影响体验
Bug: 57794
Path: http://pm.kylin.com/biz/bug-view-57794.html
> Fix: bluetooth

- plugins/account/userinfo/changegroupdialog.cpp
- plugins/account/userinfo/userinfo.cpp
- plugins/devices/printer/printer.cpp
- plugins/messages-task/notice/notice.cpp
- plugins/messages-task/search/search.cpp
- plugins/network/vpn/vpn.cpp
- plugins/personalized/wallpaper/wallpaper.cpp
- plugins/system/autoboot/autoboot.cpp
- plugins/time-language/area/area.cpp
Description: The color of the blue He font icon in the highlighted state is incorrect and not uniform
Log: 高亮状态下蓝色贺字体图标颜色不对也不统一
Task: http://pm.kylin.com/biz/task-view-33130.html
> fix(Hover State): Hover State

- plugins/system/power/power.cpp
- plugins/system/power/power.h
Description: Determine whether to support hibernation
Log: 【控制面板】电脑不支持休眠时，控制面板可以选择休眠操作但是不生效
Bug: http://pm.kylin.com/biz/bug-view-55292.html
> fix(PowerManage(sp1)): PowerManage(sp1)

- commonComponent/Uslider/uslider.cpp
- commonComponent/Uslider/uslider.h
Description: improve Uslider
Log: 刻度控件增加下标，对应刻度描述，鼠标点击可在刻度之间切换。
Task: http://pm.kylin.com/biz/task-view-33118.html
> fix(Uslider settings): Uslider settings

- plugins/messages-task/notice/notice.cpp
Description: appName nodisplay
Log: 【控制面板】电源管理界面，电源图标无文字描述
Bug: http://pm.kylin.com/biz/bug-view-55789.html
> fix(Notifycation): Notifycation

- commonComponent/Label/titlelabel.h
- plugins/account/networkaccount/configfile.cpp
- plugins/account/networkaccount/configfile.h
- plugins/account/networkaccount/maindialog.cpp
- plugins/account/networkaccount/maindialog.h
- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
- plugins/account/networkaccount/networkaccount.pro
- plugins/account/networkaccount/syncdialog.cpp
- plugins/account/networkaccount/syncdialog.h
Description: 优化弱网下交互
Log: 【云账户】断开网络，开启自动同步，未提示“无网络状态无法同步”
Bug: http://pm.kylin.com/biz/bug-view-55401.html
> fix(account):Optimazed interaction when network blocking

- plugins/time-language/datetime/worldMap/timezonechooser.cpp
- plugins/time-language/datetime/worldMap/timezonechooser.h
Description: No rounded corners in the time zone popup
Log:  时区弹窗无圆角
Task: http://pm.kylin.com/biz/task-view-33136.html
> fix(DataTime): DataTime

- plugins/account/networkaccount/mainwidget.cpp
Description: 显示错误
Log: 当同步项同步出错时，感叹号图标不会消失，除非重开。
Bug: 自测BUG
> Fix:Display error when item sync failed

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
log: 点击网络连接可以直接跳转到输入密码界面
bug: 59457
按照华为需求更改"wifi"为"WLAN"
bug:50457
>  fix(netconnect): Click the network connection to jump directly to the password interface

- plugins/devices/audio/ukmedia_input_widget.cpp
- plugins/network/vino/sharemain.cpp
- plugins/network/vino/sharemain.h
- plugins/personalized/desktop/desktop.ui
- plugins/personalized/theme/theme.cpp
- plugins/personalized/theme/theme.ui
- plugins/system/autoboot/autoboot.ui
- plugins/time-language/area/area.cpp
- plugins/time-language/area/area.ui
- plugins/time-language/datetime/worldMap/timezonechooser.cpp
Description: fix some bugs(UI)
Log: 完善某些需求的任务
> fix(fix some bugs(UI)): fix some bugs(UI)

- plugins/system/battery/battery.cpp
- plugins/system/power/power.cpp
> fix(Powermanage): Powermanage

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
log:990不支持WiFi6，过滤掉WiFi6无线网络图标显示
> fix(netconnect)The 990 does not support WiFi6，filter out icon display of WiFi6 wireless network

- plugins/security-updates/upgrade/src/updatedbus.cpp
- plugins/security-updates/upgrade/src/updatedbus.h
修复bug58211 【系统更新】更新过程中，可以进行注销/重启/关机等操作
> Fix(Upgrade): file lock failed!

- plugins/devices/shortcut/shortcut.cpp
Description:  ShortCut Hover
Log: 【系统谁在-快捷键】添加自定义快捷键按钮深色模式下效果不对+6385
Bug: https://pm.kylin.com/biz/bug-view-60910.html
> fix(ShortCut Hover):  ShortCut Hover

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
> fix(netconnect):解决当无线网卡被down掉后刷新不成功的问题

- shell/res/resfile.qrc
- shell/res/secondaryleftmenu/Search.svg
- shell/res/secondaryleftmenu/SearchWhite.svg
> Change the search icon

- shell/mainwindow.cpp
Description: 一级导航字体显示不全
Log: 修改宽度
Bug: http://zentao.kylin.com/biz/bug-view-60941.html
> fix(Mainwindow): fix bug#60941

- plugins/devices/touchpad/touchpad.cpp
- plugins/devices/touchpad/touchpad.ui
Description: touchpad optimization
Log: 触摸板优化
Bug: http://zentao.kylin.com/biz/bug-view-60889.html
> fix: touchpad optimization

- plugins/personalized/wallpaper/wallpaper.ui
- shell/modulepagewidget.cpp
- shell/modulepagewidget.ui
Description: Adjustment of secondary navigation pitch
Log: 【系统设置】二级导航标题间距不对
Bug: https://pm.kylin.com/biz/bug-view-60930.html
> fix(UI Adjust): UI Adjust

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
bug:61166
修复可连接网络中依然有已连接上的网络名称问题
bug:61140
修复网络连接状态下，控制面板网络显示无网络的问题
bug:60661
> fix(netconnect):修复快速点击网络模块插件闪退问题

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/bluetoothmain.h
- plugins/devices/bluetooth/bluetoothnamelabel.cpp
- plugins/devices/bluetooth/bluetoothnamelabel.h
- plugins/devices/bluetooth/deviceinfoitem.cpp
Description: Modify the bug
Log: 修改bug
bug：http://172.17.66.192/biz/bug-view-60067.html
http://172.17.66.192/biz/bug-view-54836.html
http://172.17.66.192/biz/bug-view-59653.html
http://172.17.66.192/biz/bug-view-57700.html
>     fix:[bluetooth]Modify the bug

- plugins/network/vino/inputpwddialog.cpp
- plugins/network/vino/sharemain.cpp
Description: Initial password display problem
Log:  【桌面共享】桌面共享的默认分享密码显示为乱码
Bug: https://pm.kylin.com/biz/bug-view-61375.html
> fix(Vino Password): Vino Password

- plugins/network/netconnect/netconnect.cpp
> fix(netconnect):Fixed an issue where the network could not be refreshed

- plugins/system/display/widget.cpp
Description: 亮度调消失问题
Log: 笔记本接口名称改变所致，同步修改
Bug: http://pm.kylin.com/biz/bug-view-61767.html
> fix(display): fix bug#61767

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/bluetoothmain.h
- plugins/devices/bluetooth/bluetoothnamelabel.cpp
- plugins/devices/bluetooth/bluetoothnamelabel.h
- plugins/devices/bluetooth/deviceinfoitem.cpp
- plugins/devices/bluetooth/deviceinfoitem.h
- shell/res/i18n/zh_CN.ts
Description: repair bug
Log: 【Bluetooth】修复bug
Bug: https://pm.kylin.com/biz/bug-view-61615.html
https://pm.kylin.com/biz/bug-view-60067.html
https://pm.kylin.com/biz/bug-view-59653.html
https://pm.kylin.com/biz/bug-view-57700.html
https://pm.kylin.com/biz/bug-view-54836.html
>     fix(Bluetooth): Bluetooth

- plugins/system/display/outputconfig.cpp
- plugins/system/display/outputconfig.h
- shell/homepagewidget.cpp
- shell/homepagewidget.h
- shell/homepagewidget.ui
- shell/mainwindow.cpp
- shell/utils/utils.cpp
- shell/utils/utils.h
Description: window adaptive size
Log: 窗口自适应大小
Task: https://pm.kylin.com/biz/story-view-6723.html
> feat: window adaptive size

- plugins/system/display/outputconfig.cpp
- plugins/system/display/outputconfig.h
Description: refresh rate restore configuration
Log: 刷新率恢复配置
Bug: https://pm.kylin.com/biz/bug-view-61416.html
> fix: refresh rate restore configuration

- plugins/security-updates/securitycenter/securitycenter.cpp
Description: Adjust Securitycenter UI
Log: 【设置】安全中心界面没有与安全中心软件保持一致
Bug: https://pm.kylin.com/biz/bug-view-61742.html (61741)
> fix(Securitycenter): Securitycenter

- .github/workflows/build.yml
- plugins/system/display/declarative/qmlscreen.cpp
Description: mouse release coordinate judgment
Log: 来回点击显示器预览，出现黑屏现象
Bug: https://pm.kylin.com/biz/bug-view-61766.html
> fix: mouse release coordinate judgment

- plugins/system/display/declarative/qmlscreen.cpp
- plugins/system/display/qml/Output.qml
- plugins/system/display/utils.cpp
- plugins/system/display/widget.cpp
Description: Interface display name change
Log: 界面显示名称更改
Bug: https://pm.kylin.com/biz/bug-view-58807.html
> fix: Interface display name change

- plugins/personalized/screensaver/screensaver.ui
- shell/res/i18n/zh_CN.ts
Description: 【屏保】建议修改屏保文案
Log: 修改文案
Bug: https://pm.kylin.com/biz/bug-view-61941.html
> fix(screensaver): fix bug#

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
- plugins/network/netconnect/netdetail.cpp
- plugins/network/netconnect/netdetail.h
- shell/res/i18n/zh_CN.ts
> Feature:Add network detail display function

- plugins/personalized/screensaver/screensaver.ui
- shell/modulepagewidget.cpp
Description: fix some Slider questions
Log: 【系统设置-网络】默认窗口大小下，代理页面开关“开启手动代理”功能引起详情内容跳动;  【系统设置】滑动条显示位置不对
Task: https://zentao.kylin.com/biz/story-view-6725.html   ;   https://zentao.kylin.com/biz/story-view-6381.html
> fix(Slider problem): Slider problem

- plugins/system/defaultapp/defaultapp.cpp
> Fix: Repeated definition

- plugins/system/battery/battery.cpp
- plugins/system/power/power.cpp
- shell/res/i18n/zh_CN.ts
> fix(Power): Power

- plugins/network/netconnect/netconnect.cpp
> fix(netconnect):Add exception handling to prevent segment errors

- plugins/system/battery/battery.cpp
- plugins/system/power/power.cpp
- shell/res/i18n/zh_CN.ts
Log: 【cpm】【HUAWEI】【KOS】【L1】【PToF】【V4试制】设置-系统-电源、电池-“空闲时间5分钟后进入睡眠”进度条改成其他时间后前面还是显示的5分钟，且该选项文字显示不全（一般+必现+不常用功能)
Bug:  https://zentao.kylin.com/biz/bug-view-62838.html (62830) (61640)
> fix(Power bugs): Power bugs

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
> fix(connect):修复双网卡时控制面板只显示一个有线网络的问题

- commonComponent/Label/iconlabel.cpp
- commonComponent/Label/iconlabel.h
- commonComponent/label.pri
- plugins/personalized/theme/theme.cpp
- plugins/personalized/theme/theme.h
- plugins/personalized/theme/theme.ui
- plugins/time-language/datetime/datetime.cpp
- plugins/time-language/datetime/worldMap/timezonechooser.cpp
- plugins/time-language/datetime/worldMap/timezonechooser.h
- plugins/time-language/datetime/worldMap/timezonemap.cpp
- plugins/time-language/datetime/worldMap/timezonemap.h
Description: Adjust  Datatime Dialog
Log: 【系统设置-时区】修改时区弹窗适配浅色主题;  【系统设置-修改时区】时区搜索控件样式效果不对
Task: https://zentao.kylin.com/biz/story-view-6721.html  ;  https://zentao.kylin.com/biz/story-view-6657.html
> fix(Datatime Dialog):  Datatime Dialog

- plugins/personalized/theme/theme.cpp
- plugins/personalized/theme/theme.ui
Description: fix button style
Log: 更改主题切换按钮样式
> fix(Theme Model): Theme Model

- shell/utils/functionselect.cpp
Description: Change homepage display
Log: 【系统设置】首页优化二级分类显示
Task: http://zentao.kylin.com/biz/story-view-6649.html
> fix(Home page display): Home page display

- plugins/devices/touchpad/touchpad.cpp
- plugins/devices/touchpad/touchpad.pro
- plugins/devices/touchpad/touchpad.ui
Description: 无法设置触控板光标移动速度
Log: 新增触控板指针速度调节滑动条
Bug:  http://pm.kylin.com/biz/bug-view-62021.html
> fix(touchpad): fix bug#62021

- plugins/time-language/datetime/worldMap/timezonechooser.cpp
Description: Adjust Datatime Dialog
Log: 【时间和日期】时区弹窗圆角显示
Bug: http://zentao.kylin.com/biz/bug-view-62755.html
> fix(Datatime Dialog): Datatime Dialog

- plugins/messages-task/about/about.cpp
- plugins/messages-task/about/about.ui
- shell/res/i18n/zh_CN.ts
Description: Adjiust About UI
Log: 【关于】在字体16时，激活状态有字体遮挡
Bug: http://zentao.kylin.com/biz/bug-view-61942.html
> fix(About UI ): About UI

- plugins/devices/audio/ukmedia_output_widget.h
Description: Modify Slider mousePressEvent
> Fix bug #61603 #61607

- plugins/account/networkaccount/blueeffect.cpp
- plugins/account/networkaccount/mainwidget.cpp
Description: Optimizing the network check
Log: 修复网络检测界面逻辑
Bug: 无
> Fix(cloud account): Optimizing the network check

- plugins/account/networkaccount/blueeffect.cpp
- plugins/account/networkaccount/mainwidget.cpp
Description: Code optimazation
Log: 【云账户】同步过程中断开网络，仍然一直提示正在同步中
Bug: http://zentao.kylin.com/biz/bug-view-62092.html
> Fix(cloud account):bug #62092

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/bluetoothmain.h
log:1.增加蓝牙开启时的多次拉起的计时器。
2.修复在没有我的设备情况下，开关蓝牙显示我的设备字样问题。
>     fix(bluetooth):Added pull - up timer when bluetooth is on

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
> fix(netconnect)Click the Network Details button for out-of-focus issues

- plugins/personalized/screenlock/screenlock.cpp
Description: Browsing the local wallpaper does not show the USB peripherals
Log: 【控制面板|锁屏】浏览本地壁纸没有显示u盘外设
Bug: https://zentao.kylin.com/biz/bug-view-63303.html
> fix(Screenlock): Screenlock

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
> fix(netconnect:)Change to a local variable to prevent the UI from floating abnormally

- plugins/personalized/theme/myqradiobutton.cpp
- plugins/personalized/theme/myqradiobutton.h
- plugins/personalized/theme/theme.cpp
- plugins/personalized/theme/theme.h
- plugins/personalized/theme/theme.pro
- plugins/personalized/theme/themewidget.cpp
- plugins/personalized/theme/themewidget.h
Description: Make some adjustments
Log: 【图标主题】图标主题选项展示的文件管理器图标与系统实际图标不一致
Bug: https://zentao.kylin.com/biz/bug-view-63148.html
> fix(Theme): Theme

- plugins/personalized/fonts/fonts.cpp
Description: font size error
Log: 字体选择项数量小于期望
Bug: http://zentao.kylin.com/biz/bug-view-63484.html
> fix: font size error

- shell/res/i18n/zh_CN.ts
Description: update translation
Log: 更新翻译
Task:http://172.17.66.192/biz/task-view-41650.html
>     chore: translation

- plugins/network/netconnect/netconnect.cpp
> fix(netconnect):修复nm-applet里删掉添加的无线网络发生闪退问题

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
- plugins/network/netconnect/netconnect.ui
> fix(netconnect):网络详情显示在对应网络下方

- shell/res/i18n/zh_CN.ts
Description: Fix Translation
Log: 【系统设置|设备】触摸板设置的描述与需求不符
Bug: https://zentao.kylin.com/biz/bug-view-62998.html
> fix(Fix Translation): Fix Translation

- plugins/account/networkaccount/mainwidget.cpp
Description:udpate user info
Log: 更新存储用户信息的方式,对应kylin-sso-client v.1.5.0
Bug: 
> Fix(cloud account):update user info

- plugins/account/networkaccount/mainwidget.cpp
Description:udpate user info
Log: 更新存储用户信息的方式,对应kylin-sso-client v.1.5.0
> Fix:Update token info

- plugins/account/networkaccount/mainwidget.cpp
Description:udpate user info
Log: 更新存储用户信息的方式,对应kylin-sso-client v.1.5.0-hw
Bug: #63457 【cpm】【HUAWEI】【KOS】【安全】【VN2】【L0】KOS系统日志中多处打印token、ip、mac地址个人数据（严重+必现+不常用)
> Fix(cloud account):Update token info

- plugins/network/netconnect/netconnect.cpp
> fix(netconnect):Exception Display “--” Network

- shell/res/i18n/zh_CN.ts
Description:  Fix Translation
Log: 【云账户】云账户同步列表中未显示最新应用名
Bug: https://zentao.kylin.com/biz/bug-view-63035.html
> fix(Fix Translation):  Fix Translation

- plugins/time-language/datetime/worldMap/timezonechooser.cpp
- plugins/time-language/datetime/worldMap/timezonemap.cpp
Log: 【需求-设置-6527】系统默认主题下。打开设置-时间语言-修改时区，右上角的关闭按钮显示不清
Bug: http://zentao.kylin.com/biz/bug-view-63928.html
> fix(Data Dialog): Data Dialog

- data/org.ukui.control-center.notice.gschema.xml
- plugins/messages-task/notice/appdetail.h
- plugins/messages-task/notice/notice.cpp
- plugins/messages-task/notice/notice.h
- plugins/messages-task/notice/notice.ui
- plugins/messages-task/notice/realizenotice.cpp
- plugins/messages-task/notice/realizenotice.h
Description: Update Notifycation
Log: 更新通知来源
> fix(Update Notifycation): Update Notifycation

- plugins/account/networkaccount/mainwidget.cpp
> Fix:Roll back to 0610 version

- plugins/messages-task/notice/appdetail.cpp
- plugins/messages-task/notice/appdetail.h
- plugins/messages-task/notice/notice.cpp
- plugins/messages-task/notice/notice.h
- plugins/messages-task/notice/notice.ui
- plugins/messages-task/notice/realizenotice.cpp
- plugins/messages-task/notice/realizenotice.h
Description:  Noyifycation Update
Log: 更新通知
> fix(Noyifycation Update):  Noyifycation Update

- plugins/devices/audio/ukmedia_main_widget.cpp
>  Fix #bug61360

- shell/res/i18n/zh_CN.ts
> fix(netconnect):需求变更将“打开WiFi”改为“打开WLAN”

- plugins/network/netconnect/netconnect.cpp
> fix(netconnect):Caton for 15 seconds

- plugins/system/defaultapp/defaultapp.cpp
Description:  【设置】修改默认浏览器的不生效，并且产生core文件
Log: bug63479
> fix(defaultapp): fix core thread

- plugins/system/display/widget.cpp
Log: 【控制面板】每次打开夜间模式，生效方式没有默认选项，手动设置为跟随日出日落后保存，重新打开控制面板发现自动变为自定义时间
Bug: http://zentao.kylin.com/biz/bug-view-61992.html
> fix(Night Model): Night Model (优麒麟)

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
> fix(netconnect):Wireless switch synchronization

- plugins/account/networkaccount/mainwidget.cpp
- plugins/account/networkaccount/mainwidget.h
Description: Change path of user info
Log: 更换用户信息保存方式
> Fix:Change path of user info

- plugins/account/networkaccount/mainwidget.cpp
Descrption:Auto-sync switch close abnomal
Log:自动同步开关关闭异常
Bug:65268
> Fix(cloud account):Auto-sync switch close abnomal

- plugins/account/networkaccount/mainwidget.cpp
> Fix(cloud account):change user info file name

- plugins/account/networkaccount/mainwidget.cpp
> Fix:Change user info file name

- plugins/system/display/controlpanel.cpp
- plugins/system/display/controlpanel.h
- plugins/system/display/display.pro
- plugins/system/display/outputconfig.cpp
- plugins/system/display/outputconfig.h
- plugins/system/display/resolutionslider.cpp
- plugins/system/display/resolutionslider.h
- plugins/system/display/scalesize.h
- plugins/system/display/widget.cpp
- plugins/system/display/widget.h
- shell/res/i18n/zh_CN.ts
Description: Fix Scale
Log: 【控制面板】单屏设置缩放150%、175%注销后没有生效   ;    【双屏】拔掉4k屏，VGA屏无法自适应
Bug: https://zentao.kylin.com/biz/bug-view-61980.html  ; https://zentao.kylin.com/biz/bug-view-64692.html
> fix(Fix Scale ): Fix Scale

- data/org.ukui.control-center.notice.gschema.xml
- plugins/system/power/power.cpp
Description: Power and Notifycation
Log: 修复一些问题
> fix(Power and Notifycation): Power and Notifycation

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/config.h
- plugins/devices/bluetooth/deviceinfoitem.cpp
- shell/res/i18n/zh_CN.ts
Description: bluetooth
Log: 【cpm】【BT】KV测试机连上KV辅助机后断开状态，不显示已配对
【蓝牙】蓝牙设备列表概率性不显示内容
【cpm】【BT】测试机打开搜索蓝牙设备是，测试机会一直保持搜索，但列表为空
【cpm】【BT】蓝牙传输文件不弹文件接收窗口
【蓝牙】发送文件至笔记本，发送失败
bug:http://pm.kylin.com/biz/bug-view-65086.html
http://zentao.kylin.com/biz/bug-view-63030.html
http://zentao.kylin.com/biz/bug-view-65086.html
http://zentao.kylin.com/biz/bug-view-64909.html
http://zentao.kylin.com/biz/bug-view-64505.html
>             fix(bluetooth): bluetooth fix bug

- plugins/devices/bluetooth/bluetoothmain.cpp
- plugins/devices/bluetooth/bluetoothmain.h
Description: 修复蓝牙服务重启后出现重复UI
Log:
> fix(Bluetooth): 处理蓝牙服务重启问题

- plugins/system/display/controlpanel.cpp
- plugins/system/display/outputconfig.cpp
- plugins/system/display/outputconfig.h
Description: Fix Scale (sp1-0610)
Log: 修复有显示器添加和移除时未及时更新缩放率列表的问题
> fix(Fix Scale (sp1-0610)): Fix Scale (sp1-0610)

- commonComponent/Label/fixlabel.cpp
- commonComponent/Label/fixlabel.h
- plugins/system/display/brightnessFrame.cpp
- plugins/system/display/brightnessFrame.h
- plugins/system/display/controlpanel.cpp
- registeredQDbus/sysdbusregister.cpp
- registeredQDbus/sysdbusregister.h
2、亮度逻辑修改，一般情况下不再卡顿和延时，不影响控制面板打开
3、修改亮度条显示UI，名字长时使用省略号
>     1、修复同个显示器显示多条刷新率等信息问题

- plugins/messages-task/about/about.cpp
- shell/res/i18n/zh_CN.ts
Description: Change search centent
Log: 【控制面板|搜索】设置内部分功能无法搜索到
Bug: http://172.17.66.192/biz/bug-view-52232.html
> fix(Change search centent): Change search centent

- plugins/system/display/controlpanel.cpp
- plugins/system/display/controlpanel.h
- plugins/system/display/display.pro
- plugins/system/display/outputconfig.cpp
- plugins/system/display/outputconfig.h
- plugins/system/display/resolutionslider.cpp
- plugins/system/display/resolutionslider.h
- plugins/system/display/scalesize.h
- plugins/system/display/widget.cpp
- plugins/system/display/widget.h
Description: Scale
Log: 同步缩放改动
> fix(Display ): Display

- plugins/devices/touchpad/touchpad.cpp
Description:  Fix Touchpad Question
Log: 【控制面板|触摸板】设置插入鼠标时候禁用触摸板不生效
> fix(Touchpad): Touchpad

- plugins/system/display/display.ui
- plugins/system/display/widget.cpp
- shell/res/i18n/zh_CN.ts
Description: Change Translator
Log: 【cpm】【HUAWEI】【Graphic】【VN2】【L1】VGA接部分显示器修改分辨率黑屏时间过长导致分辨率无法确认应用（2台显示器黑屏12s左右，一台显示器黑屏30s左右，1台显示器8s左右）（一般+高概率4/5+常用功能）;   【内测】【控制面板】【65736】英文模式，F8快捷键镜像模式设置与控制面板显示不统一
Bug: http://172.17.66.192/biz/bug-view-66509.html  ;   http://172.17.66.192/biz/bug-view-53017.html
> fix(Change Translator): Change Translator

- plugins/network/netconnect/netconnect.cpp
- plugins/network/netconnect/netconnect.h
> fix(netconnect):点击连接网络连接直接跳转到对应网络连接界面

- plugins/system/power/power.cpp
Description: Power(990)
Log: 【cpm】【HUAWEI】【电源管理】【V4】【L1】系统的电源和电池界面设计待优化。(一般+必现+常用功能)。
Bug: http://172.17.66.192/biz/bug-view-62565.html
> fix(Power(990)): Power(990)

- plugins/network/netconnect/netconnect.cpp
> fix(netconnect):修复部分机器点击控制面板网络闪退问题

- plugins/system/power/power.cpp
- plugins/system/power/power.h
- plugins/system/power/powermacrodata.h
Description: Power(sp1)
Log: 电源管理的设计（架构支持X86、ARM、龙芯） / 电源管理的设计（架构支持X86、ARM、龙芯）
Task: http://172.17.66.192/biz/task-view-42519.html
> fix(Power(sp1)): Power(sp1)

- plugins/devices/bluetooth/bluetoothmain.cpp
Description: bluetooth
Log: 配对成功后我的设备列表中增加多个设备的问题
>         fix(bluetooth): bluetooth

- plugins/system/display/controlpanel.cpp
- plugins/system/display/outputconfig.cpp
- plugins/system/display/widget.cpp
Description: Display Scale (990)
Log: 去掉改变缩放的提示弹窗，根据新方案更改缩放选项，根据显示屏是否关闭作相应的缩放选项处理
> fix(Display Scale (990)): Display Scale (990)

- plugins/messages-task/about/about.cpp
Description:  About (username)
Log: 【控制面板】修改用户名后关于界面"用户名"显示不会更新
Bug: http://172.17.66.192/biz/bug-view-68750.html
> fix(About (username)):  About (username)

- plugins/system/display/unifiedoutputconfig.cpp
Description: Display (Unified scale)
Log: 修复统一输出下，恢复设置未刷新缩放选项的问题
> fix(Display (Unified scale)): Display (Unified scale)
